local clothmarker1 = createMarker(217.447265625, -98.6455078125, 1004.2578125,"cylinder",2,0,200,0,50) -- Binco, Ganton LS
setElementInterior(clothmarker1, 15)
setElementDimension(clothmarker1, 163)

local clothmarker2 = createMarker(217.447265625, -98.6455078125, 1004.2578125,"cylinder",2,0,200,0,50) -- Binco, Ganton LS
setElementInterior(clothmarker2, 15)
setElementDimension(clothmarker2, 175)

-- local clothmarker2 = createMarker(197.755859375, -131.837890625, 1002.5078125, "cylinder",2,0,200,0,50) -- Las Barrancas
-- setElementInterior(clothmarker2, 3)
-- setElementDimension(clothmarker2, 216)


clothes = { [0] = { 		[1] = {idUnico = 2, Nombre = "Tirantes Negra", Texture = "vestblack", Model = "vest", price = 50},
							[2] =  {idUnico = 3, Nombre = "Tirantes Blanca", Texture = "vest", Model = "vest", price = 50 },
							[3] =  {idUnico = 4, Nombre = "Camiseta Rayas", Texture = "tshirt2horiz", Model = "tshirt2", price = 75 },
							[4] =  {idUnico = 5, Nombre = "Camiseta Blanca", Texture = "tshirtwhite", Model = "tshirt", price = 75 },
							[5] =  {idUnico = 6, Nombre = "Camiseta LS", Texture = "tshirtilovels", Model = "tshirt", price = 75 },
							[6] =  {idUnico = 7, Nombre = "Camiseta Homies", Texture = "tshirtblunts", Model = "tshirt", price = 75 },
							[7] =  {idUnico = 8, Nombre = "Camisa Roja Desabrochada", Texture = "shirtbplaid", Model = "shirtb", price = 75 },
							[8] =  {idUnico = 9, Nombre = "Camisa Azul Cuadros", Texture = "shirtbcheck", Model = "shirtb", price = 75 },
							[9] =  {idUnico = 11, Nombre = "Chaqueta Beis Desabrochada", Texture = "field", Model = "field", price = 100 },
							[10] =  {idUnico = 12, Nombre = "Camiseta Verde", Texture = "tshirterisyell", Model = "tshirt", price = 100 },
							[11] =  {idUnico = 13, Nombre = "Camiseta Naranja", Texture = "tshirterisorn", Model = "tshirt", price = 100 },
							[12] =  {idUnico = 14, Nombre = "Camiseta Deporte", Texture = "trackytop2eris", Model = "trackytop1", price = 100 },
							[13] =  {idUnico = 15, Nombre = "Chaqueta Roja y Blanca Desabrochada", Texture = "bbjackrim", Model = "bbjack", price = 100 },
							[14] =  {idUnico = 16, Nombre = "Chaqueta Roja y Negra Desabrochada", Texture = "bballjackrstar", Model = "bbjack", price = 100 },
							[15] =  {idUnico = 17, Nombre = "Tirantes Basket 1", Texture = "baskballdrib", Model = "baskball", price = 125 },
							[16] =  {idUnico = 18, Nombre = "Tirantes Basket 2", Texture = "baskballrim", Model = "baskball", price = 125 },
							[17] =  {idUnico = 19, Nombre = "Camiseta Azul", Texture = "sixtyniners", Model = "tshirt", price = 125 },
							[18] =  {idUnico = 20, Nombre = "Camiseta Beisbol", Texture = "bandits", Model = "baseball", price = 125 },
							[19] =  {idUnico = 21, Nombre = "Camiseta Roja con Flecha", Texture = "tshirtprored", Model = "tshirt", price = 125 },
							[20] =  {idUnico = 22, Nombre = "Camiseta Negra Prolaps", Texture = "tshirtproblk", Model = "tshirt", price = 125 },
							[21] =  {idUnico = 23, Nombre = "Chaqueta Chandal 1", Texture = "trackytop1pro", Model = "trackytop1", price = 175 },
							[22] =  {idUnico = 24, Nombre = "Jersey Hockey", Texture = "hockeytop", Model = "sweat", price = 175 },
							[23] =  {idUnico = 25, Nombre = "Jersey Verde y Blanco", Texture = "bbjersey", Model = "sleevt", price = 175 },
							[24] =  {idUnico = 26, Nombre = "Chaqueta Chandal 2", Texture = "shellsuit", Model = "trackytop1", price = 175 },
							[25] =  {idUnico = 27, Nombre = "Camiseta Blanca con Herradura", Texture = "tshirtheatwht", Model = "tshirt", price = 200 },
							[26] =  {idUnico = 28, Nombre = "Camiseta Dragon", Texture = "tshirtbobomonk", Model = "tshirt", price = 200},
							[27] =  {idUnico = 29, Nombre = "Camiseta Roja 80", Texture = "tshirtbobored", Model = "tshirt", price = 200 },
							[28] =  {idUnico = 30, Nombre = "Camiseta Blanca 5", Texture = "tshirtbase5", Model = "tshirt", price = 200 },
							[29] =  {idUnico = 31, Nombre = "Camiseta SubUrban", Texture = "tshirtsuburb", Model = "tshirt", price = 200 },
							[30] =  {idUnico = 32, Nombre = "Sudadera Gris", Texture = "hoodyamerc", Model = "hoodya", price = 500 },
							[31] =  {idUnico = 33, Nombre = "Sudadera Verde", Texture = "hoodyabase5", Model = "hoodya", price = 500 },
							[32] =  {idUnico = 34, Nombre = "Sudadera Rockstar Blanca", Texture = "hoodyarockstar", Model = "hoodya", price = 500 },
							[33] =  {idUnico = 35, Nombre = "Camiseta Blanca con Chaleco Azul", Texture = "wcoatblue", Model = "wcoat", price = 200 },
							[34] =  {idUnico = 36, Nombre = "Abrigo Verde", Texture = "coach", Model = "coach", price = 250 },
							[35] =  {idUnico = 37, Nombre = "Abrigo Azul", Texture = "coachsemi", Model = "coach", price = 250 },
							[36] =  {idUnico = 38, Nombre = "Jersey Rockstar", Texture = "sweatrstar", Model = "sweat", price = 300 },
							[37] =  {idUnico = 39, Nombre = "Sudadera Rockstar Azul", Texture = "hoodyAblue", Model = "hoodyA", price = 500 },
							[38] =  {idUnico = 40, Nombre = "Sudadera Rockstar Negra", Texture = "hoodyAblack", Model = "hoodyA", price = 500 },
							[39] =  {idUnico = 41, Nombre = "Sudadera Rockstar Verde", Texture = "hoodyAgreen", Model = "hoodyA", price = 500 },
							[40] =  {idUnico = 42, Nombre = "Camiseta Larga Marron", Texture = "sleevtbrown", Model = "sleevt", price = 350 },
							[41] =  {idUnico = 43, Nombre = "Camisa Azul y Blanca", Texture = "shirtablue", Model = "shirta", price = 300 },
							[42] =  {idUnico = 44, Nombre = "Camisa Amarilla y Blanca", Texture = "shirtayellow", Model = "shirta", price = 300 },
							[43] =  {idUnico = 45, Nombre = "Camisa Gris y Blanca", Texture = "shirtagrey", Model = "shirta", price = 300 },
							[44] =  {idUnico = 46, Nombre = "Camisa Verde y Blanca", Texture = "shirtbgang", Model = "shirtb", price = 250 },
							[45] =  {idUnico = 47, Nombre = "Camiseta ZIP Crema", Texture = "tshirtzipcrm", Model = "tshirt", price = 300 },
							[46] =  {idUnico = 48, Nombre = "Camiseta ZIP Gris", Texture = "tshirtzipgry", Model = "tshirt", price = 300 },
							[47] =  {idUnico = 49, Nombre = "Camisa Vaquera Desabrochada", Texture = "denimfade", Model = "denim", price = 500 },
							[48] =  {idUnico = 50, Nombre = "Camisa Bolera", Texture = "bowling", Model = "hawaii", price = 400 },
							[49] =  {idUnico = 51, Nombre = "Sudadera Desabrochada Beis", Texture = "hoodjackbeige", Model = "hoodjack", price = 400 },
							[50] =  {idUnico = 52, Nombre = "Tirantes Basket 3", Texture = "baskballloc", Model = "baskball", price = 200 },
							[51] =  {idUnico = 53, Nombre = "Camiseta Esposas Gris", Texture = "tshirtlocgrey", Model = "tshirt", price = 250 },
							[52] =  {idUnico = 54, Nombre = "Camiseta Uzi Gris", Texture = "tshirtmaddgrey", Model = "tshirt", price = 250 },
							[53] =  {idUnico = 55, Nombre = "Camiseta Uzi Verde", Texture = "tshirtmaddgrn", Model = "tshirt", price = 250 },
							[54] =  {idUnico = 56, Nombre = "Traje Gris 1", Texture = "suit1grey", Model = "suit1", price = 500 },
							[55] =  {idUnico = 57, Nombre = "Traje Negro", Texture = "suit1blk", Model = "suit1", price = 500 },
							[56] =  {idUnico = 58, Nombre = "Chaqueta de Cuero con Camiseta Lobo", Texture = "leather", Model = "leather", price = 1000 },
							[57] =  {idUnico = 59, Nombre = "Chaqueta Morada Ballas", Texture = "painter", Model = "painter", price = 400 },
							[58] =  {idUnico = 60, Nombre = "Camisa Hawai 1", Texture = "hawaiiwht", Model = "hawaii", price = 400 },
							[59] =  {idUnico = 61, Nombre = "Camisa Hawai 2", Texture = "hawaiired", Model = "hawaii", price = 400 },
							[60] =  {idUnico = 62, Nombre = "Chaqueta Deporte", Texture = "sportjack", Model = "trackytop1", price = 350 },
							[61] =  {idUnico = 63, Nombre = "Traje Rojo", Texture = "suit1red", Model = "suit1", price = 500 },
							[62] =  {idUnico = 64, Nombre = "Traje Azul Claro", Texture = "suit1blue", Model = "suit1", price = 500 },
							[63] =  {idUnico = 65, Nombre = "Traje Amarillo", Texture = "suit1yellow", Model = "suit1", price = 500 },
							[64] =  {idUnico = 66, Nombre = "Traje Gris 2", Texture = "suit2grn", Model = "suit2", price = 750 },
							[65] =  {idUnico = 67, Nombre = "Traje Negro 2", Texture = "tuxedo", Model = "suit2", price = 500 },
							[66] =  {idUnico = 68, Nombre = "Traje Verde", Texture = "suit1gang", Model = "suit1", price = 500 },
							[67] =  {idUnico = 69, Nombre = "Traje Azul Oscuro con R", Texture = "letter", Model = "sleevt", price = 500 },
							[68] = {idUnico = 1, Nombre = "Sin Camiseta", Texture = "player_torso", Model = "torso", price = 0}},

			[1] = {			[1] = {idUnico = 71, Nombre = "Muy Corto Rubio", Texture = "hairblond", Model = "head", price = 75 },
							[2] = {idUnico = 72, Nombre = "Muy Corto Rojo", Texture = "hairred", Model = "head", price = 75 },
							[3] = {idUnico = 73, Nombre = "Muy Corto Azul", Texture = "hairblue", Model = "head", price = 75 },
							[4] = {idUnico = 74, Nombre = "Muy Corto Verde", Texture = "hairgreen", Model = "head", price = 75 },
							[5] = {idUnico = 75, Nombre = "Muy Corto Rosa", Texture = "hairpink", Model = "head", price = 75 },
							[6] = {idUnico = 76, Nombre = "Rapado", Texture = "bald", Model = "head", price = 75 },
							[7] = {idUnico = 77, Nombre = "Rapado con Bigote y Barba 1", Texture = "baldbeard", Model = "head", price = 75 },
							[8] = {idUnico = 78, Nombre = "Rapado con Bigote", Texture = "baldtash", Model = "head", price = 75 },
							[9] = {idUnico = 79, Nombre = "Rapado con Bigote y Barba 2", Texture = "baldgoatee", Model = "head", price = 75 },
							[10] = {idUnico = 80, Nombre = "Muy Corto Castaño sin Laterales", Texture = "highfade", Model = "head", price = 75 },
							[11] = {idUnico = 81, Nombre = "Corto Sin Laterales", Texture = "highafro", Model = "highafro", price = 100 },
							[12] = {idUnico = 82, Nombre = "Corto 1", Texture = "wedge", Model = "wedge", price = 100 },
							[13] = {idUnico = 83, Nombre = "Corto Levantado", Texture = "slope", Model = "slope", price = 100 },
							[14] = {idUnico = 84, Nombre = "Rizado", Texture = "jhericurl", Model = "jheri", price = 100 },
							[15] = {idUnico = 85, Nombre = "Mechas Castaño", Texture = "cornrows", Model = "cornrows", price = 250 },
							[16] = {idUnico = 86, Nombre = "Mechas Rubio", Texture = "cornrowsb", Model = "cornrows", price = 250 },
							[17] = {idUnico = 87, Nombre = "Corto con Franjas Laterales", Texture = "tramline", Model = "tramline", price = 75 },
							[18] = {idUnico = 88, Nombre = "Muy Corto Defectuoso", Texture = "groovecut", Model = "groovecut", price = 75 },
							[19] = {idUnico = 89, Nombre = "Cresta Castaño", Texture = "mohawk", Model = "mohawk", price = 150 },
							[20] = {idUnico = 90, Nombre = "Cresta Rubio", Texture = "mohawkblond", Model = "mohawk", price = 150 },
							[21] = {idUnico = 91, Nombre = "Cresta Rosa", Texture = "mohawkpink", Model = "mohawk", price = 150 },
							[22] = {idUnico = 92, Nombre = "Cresta Castaño con Bigote y Barba", Texture = "mohawkbeard", Model = "mohawk", price = 250 },
							[23] = {idUnico = 93, Nombre = "Afro Castaño", Texture = "afro", Model = "afro", price = 250 },
							[24] = {idUnico = 94, Nombre = "Afro Castaño con Bigote", Texture = "afrotash", Model = "afro", price = 250 },
							[25] = {idUnico = 95, Nombre = "Afro Castaño con Bigote y Barba", Texture = "afrobeard", Model = "afro", price = 300 },
							[26] = {idUnico = 96, Nombre = "Afro Rubio", Texture = "afroblond", Model = "afro", price = 250 },
							[27] = {idUnico = 97, Nombre = "Corto 2", Texture = "flattop", Model = "flattop", price = 200 },
							[28] = {idUnico = 98, Nombre = "Corto 3 (Elvis)", Texture = "elvishair", Model = "elvishair", price = 200 },
							[29] = {idUnico = 99, Nombre = "Muy Corto Castaño con Bigote y Barba", Texture = "beard", Model = "head", price = 175 },
							[30] = {idUnico = 100, Nombre = "Muy Corto con Bigote", Texture = "tash", Model = "head", price = 75 },
							[31] = {idUnico = 101, Nombre = "Muy Corto con Bigote y Barba", Texture = "goatee", Model = "head", price = 75 },
							[32] = {idUnico = 70, Nombre = "Muy Corto Castaño", Texture = "player_face", Model = "head", price = 50 }},
							-- Repetido con ID 25
							--[33] = {idUnico = 102, Nombre = "", Texture = "afrogoatee", Model = "afro", price = 175 }},
							
			[2] = { 		
							[1] = {idUnico = 104, Nombre = "Vaqueros Militar Verde", Texture = "worktrcamogrn", Model = "worktr", price = 300 },
							[2] = {idUnico = 105, Nombre = "Vaqueros Militar Gris", Texture = "worktrcamogry", Model = "worktr", price = 300 },
							[3] = {idUnico = 106, Nombre = "Vaqueros Gris", Texture = "worktrgrey", Model = "worktr", price = 250 },
							[4] = {idUnico = 107, Nombre = "Vaqueros Verde Pistacho", Texture = "worktrkhaki", Model = "worktr", price = 250 },
							[5] = {idUnico = 108, Nombre = "Pantalón Chandal Blanco", Texture = "tracktr", Model = "tracktr", price = 100 },
							[6] = {idUnico = 109, Nombre = "Pantalón Chandal Azul con Franjas Rojas", Texture = "tracktreris", Model = "tracktr", price = 100 },
							[7] = {idUnico = 110, Nombre = "Vaqueros Azules", Texture = "jeansdenim", Model = "jeans", price = 150 },
							[8] = {idUnico = 111, Nombre = "Calzoncillos Negros", Texture = "legsblack", Model = "legs", price = 50 },
							[9] = {idUnico = 112, Nombre = "Calzoncillos con Corazones", Texture = "legsheart", Model = "legs", price = 50 },
							[10] = {idUnico = 113, Nombre = "Chinos Blancos", Texture = "biegetr", Model = "chinosb", price = 150 },
							[11] = {idUnico = 114, Nombre = "Pantalón Chandal Rojo con Franjas Blancas", Texture = "tracktrpro", Model = "tracktr", price = 100 },
							[12] = {idUnico = 115, Nombre = "Pantalón Chandal Negro con Franjas Blancas", Texture = "tracktrwhstr", Model = "tracktr", price = 100 },
							[13] = {idUnico = 116, Nombre = "Pantalón Chandal Azul con Franjas Blancas", Texture = "tracktrblue", Model = "tracktr", price = 100 },
							[14] = {idUnico = 117, Nombre = "Pantalón Chandal Verde con Franjas Blancas", Texture = "tracktrgang", Model = "tracktr", price = 100 },
							[15] = {idUnico = 118, Nombre = "Pantalón Corto Blancos", Texture = "bbshortwht", Model = "boxingshort", price = 75 },
							[16] = {idUnico = 119, Nombre = "Pantalón Corto Rojo y Blanco 1", Texture = "boxshort", Model = "boxingshort", price = 75 },
							[17] = {idUnico = 120, Nombre = "Pantalón Corto Rojo y Blanco 2", Texture = "bbshortred", Model = "boxingshort", price = 75 },
							[18] = {idUnico = 121, Nombre = "Pantalón Chandal 2", Texture = "shellsuittr", Model = "tracktr", price = 100 },
							[19] = {idUnico = 122, Nombre = "Pantalón Corto Gris", Texture = "shortsgrey", Model = "shorts", price = 125 },
							[20] = {idUnico = 123, Nombre = "Pantalón Corto Verde Pistacho", Texture = "shortskhaki", Model = "shorts", price = 125 },
							[21] = {idUnico = 124, Nombre = "Pantalón SemiCorto Gris", Texture = "chongergrey", Model = "chonger", price = 125 },
							[22] = {idUnico = 125, Nombre = "Pantalón SemiCorto Verde", Texture = "chongergang", Model = "chonger", price = 125 },
							[23] = {idUnico = 126, Nombre = "Pantalón SemiCorto Rojo", Texture = "chongerred", Model = "chonger", price = 125 },
							[24] = {idUnico = 127, Nombre = "Pantalón SemiCorto Azul", Texture = "chongerblue", Model = "chonger", price = 125 },
							[25] = {idUnico = 128, Nombre = "Pantalón Corto Verde", Texture = "shortsgang", Model = "shorts", price = 125 },
							[26] = {idUnico = 129, Nombre = "Vaqueros Verdes", Texture = "denimsgang", Model = "jeans", price = 300 },
							[27] = {idUnico = 130, Nombre = "Vaqueros Rojos", Texture = "denimsred", Model = "jeans", price = 300 },
							[28] = {idUnico = 131, Nombre = "Chinos Beis", Texture = "chinosbiege", Model = "chinosb", price = 250 },
							[29] = {idUnico = 132, Nombre = "Chinos Gris", Texture = "chinoskhaki", Model = "chinosb", price = 250 },
							[30] = {idUnico = 133, Nombre = "Chinos Cortos Beis", Texture = "cutoffchinos", Model = "shorts", price = 75 },
							[31] = {idUnico = 134, Nombre = "Chinos Cortos Azules", Texture = "cutoffchinosblue", Model = "shorts", price = 75 },
							[32] = {idUnico = 135, Nombre = "Chinos Negros", Texture = "chinosblack", Model = "chinosb", price = 150 },
							[33] = {idUnico = 136, Nombre = "Chinos Azules", Texture = "chinosblue", Model = "chinosb", price = 150 },
							[34] = {idUnico = 137, Nombre = "Vaqueros Marcados con Cinturón Negro", Texture = "leathertr", Model = "leathertr", price = 750 },
							[35] = {idUnico = 138, Nombre = "Vaqueros Marcados con Cinturón Negro (Manchados)", Texture = "leathertrchaps", Model = "leathertr", price = 750 },
							[36] = {idUnico = 139, Nombre = "Vaqueros con Cinturón Gris", Texture = "suit1trgrey", Model = "suit1tr", price = 150 },
							[37] = {idUnico = 140, Nombre = "Vaqueros con Cinturón Negro", Texture = "suit1trblk", Model = "suit1tr", price = 200 },
							[38] = {idUnico = 141, Nombre = "Vaqueros Azules Cortos", Texture = "cutoffdenims", Model = "", price = 200 },
							[39] = {idUnico = 142, Nombre = "Vaqueros con Cinturón Rojo", Texture = "suit1trred", Model = "suit1tr", price = 400 },
							[40] = {idUnico = 143, Nombre = "Vaqueros con Cinturón Azules", Texture = "suit1trblue", Model = "suit1tr", price = 400 },
							[41] = {idUnico = 144, Nombre = "Vaqueros con Cinturón Amarillos", Texture = "suit1tryellow", Model = "suit1tr", price = 400 },
							[42] = {idUnico = 145, Nombre = "Vaqueros con Cinturón Verde Pistacho", Texture = "suit1trgreen", Model = "suit1tr", price = 400 },
							-- Repetido ID 37
							--[43] = {idUnico = 146, Nombre = "", Texture = "suit1trblk2", Model = "suit1tr", price = 400 },
							[43] = {idUnico = 147, Nombre = "Vaqueros con Cinturón Verdes", Texture = "suit1trgang", Model = "suit1tr", price = 400 },
							[44] = {idUnico = 103, Nombre = "Calzoncillos Blancos", Texture = "player_legs", Model = "legs", price = 25 }},
			
			[3] = {			[1] = {idUnico = 149, Nombre = "Botas Cowboy 1", Texture = "cowboyboot2", Model = "biker", price = 500 },
							[2] = {idUnico = 150, Nombre = "Zapatillas Basket 1", Texture = "bask2semi", Model = "bask1", price = 250 },
							[3] = {idUnico = 151, Nombre = "Zapatillas Basket 2", Texture = "bask1eris", Model = "bask1", price = 250 },
							[4] = {idUnico = 152, Nombre = "Zapatillas Verdes", Texture = "sneakerbincgang", Model = "sneaker", price = 250 },
							[5] = {idUnico = 153, Nombre = "Zapatillas Azules 1", Texture = "sneakerbincblu", Model = "sneaker", price = 250 },
							[6] = {idUnico = 154, Nombre = "Zapatillas Negras", Texture = "sneakerbincblk", Model = "sneaker", price =  250},
							[7] = {idUnico = 155, Nombre = "Sandalias", Texture = "sandal", Model = "flipflop", price = 75 },
							[8] = {idUnico = 156, Nombre = "Sandalias con Calcetines", Texture = "sandalsock", Model = "flipflop", price = 75 },
							[9] = {idUnico = 157, Nombre = "Chanclas", Texture = "flipflop", Model = "flipflop", price = 75 },
							[10] = {idUnico = 158, Nombre = "Zapatillas Basket 3", Texture = "hitop", Model = "bask1", price = 250 },
							[11] = {idUnico = 159, Nombre = "Converse Negras 1", Texture = "convproblk", Model = "conv", price = 250 },
							[12] = {idUnico = 160, Nombre = "Converse Azules", Texture = "convproblu", Model = "conv", price = 250 },
							[13] = {idUnico = 161, Nombre = "Converse Verdes", Texture = "convprogrn", Model = "conv", price = 250 },
							[14] = {idUnico = 162, Nombre = "Zapatillas Rojas 1", Texture = "sneakerprored", Model = "sneaker", price = 250 },
							[15] = {idUnico = 163, Nombre = "Zapatillas Azules 2", Texture = "sneakerproblu", Model = "sneaker", price = 250 },
							[16] = {idUnico = 164, Nombre = "Zapatillas Blancas 1", Texture = "sneakerprowht", Model = "sneaker", price = 250 },
							[17] = {idUnico = 165, Nombre = "Zapatillas Basket 4", Texture = "bask1prowht", Model = "bask1", price = 250 },
							[18] = {idUnico = 166, Nombre = "Zapatillas Basket 5", Texture = "bask1problk", Model = "bask1", price =  250},
							[19] = {idUnico = 167, Nombre = "Botas Cowboy 2", Texture = "boxingshoe", Model = "biker", price = 500 },
							[20] = {idUnico = 168, Nombre = "Converse Negras 2", Texture = "convheatblk", Model = "conv", price = 250 },
							[21] = {idUnico = 169, Nombre = "Converse Rojas", Texture = "convheatred", Model = "conv", price = 250 },
							[22] = {idUnico = 170, Nombre = "Converse Naranjas", Texture = "convheatorn", Model = "conv", price = 250 },
							[23] = {idUnico = 171, Nombre = "Zapatillas Blancas 2", Texture = "sneakerheatwht", Model = "sneaker", price = 250 },
							[24] = {idUnico = 172, Nombre = "Zapatillas Grises", Texture = "sneakerheatgry", Model = "sneaker", price = 250 },
							[25] = {idUnico = 173, Nombre = "Zapatillas Negras 3", Texture = "sneakerheatblk", Model = "sneaker", price = 250 },
							[26] = {idUnico = 174, Nombre = "Zapatillas Basket 6", Texture = "bask2heatwht", Model = "bask1", price = 250 },
							[27] = {idUnico = 175, Nombre = "Zapatillas Basket 7", Texture = "bask2heatband", Model = "bask1", price = 250 },
							[28] = {idUnico = 176, Nombre = "Zapatillas Negras 3", Texture = "timbergrey", Model = "bask1", price = 250 },
							[29] = {idUnico = 177, Nombre = "Zapatillas Rojas 2", Texture = "timberred", Model = "bask1", price = 250 },
							[30] = {idUnico = 178, Nombre = "Zapatillas Beis", Texture = "timberfawn", Model = "bask1", price = 250 },
							[31] = {idUnico = 179, Nombre = "Zapatillas Militares", Texture = "timberhike", Model = "bask1", price = 250 },
							[32] = {idUnico = 180, Nombre = "Botas Cowboy 3", Texture = "cowboyboot", Model = "biker", price = 500 },
							[33] = {idUnico = 181, Nombre = "Botas Cowboy 4", Texture = "biker", Model = "biker", price = 500 },
							[34] = {idUnico = 182, Nombre = "Botas Cowboy 5", Texture = "snakeskin", Model = "biker", price = 500 },
							[35] = {idUnico = 183, Nombre = "Zapatos Negros", Texture = "shoedressblk", Model = "shoe", price = 300 },
							[36] = {idUnico = 184, Nombre = "Zapatos Marrones", Texture = "shoedressbrn", Model = "shoe", price = 300 },
							[37] = {idUnico = 185, Nombre = "Zapatos Negros (Defectuoso)", Texture = "shoespatz", Model = "shoe", price = 300 },
							[38] = {idUnico = 148, Nombre = "Descalzo", Texture = "foot", Model = "feet", price = 0}},
							
			[4] = {			[1] = {idUnico = 186, Nombre = "Hierba, Marihuana", Texture = "4WEED", Model = "4weed", price = 300 },
							[2] = {idUnico = 187, Nombre = "Cruz", Texture = "4RIP", Model = "4rip", price = 300 },
							[3] = {idUnico = 188, Nombre = "Araña", Texture = "4SPIDER", Model = "4spider", price = 300 } },
			
			[5] = { 		[1] = {idUnico = 189, Nombre = "Gun", Texture = "5GUN", Model = "5gun", price = 300 },
							[2] = {idUnico = 190, Nombre = "Cruz", Texture = "5CROSS", Model = "5cross", price = 300 },
							[3] = {idUnico = 191, Nombre = "Cross", Texture = "5CROSS2", Model = "5cross2", price = 300 },
							[4] = {idUnico = 192, Nombre = "Cross 2", Texture = "5CROSS3", Model = "5cross3", price = 300 }},
			
			[6] = {			[1] = {idUnico = 193, Nombre = "Azteca", Texture = "6AZTEC", Model = "6aztec", price = 300 },
							[2] = {idUnico = 194, Nombre = "Crown", Texture = "6CROWN", Model = "6crown", price = 300 },
							[3] = {idUnico = 195, Nombre = "Clown", Texture = "6CLOWN", Model = "6clown", price = 300 },
							[4] = {idUnico = 196, Nombre = "Azteca", Texture = "6AFRICA", Model = "6africa", price = 300 } },
			
			[7] = { 		[1] = {idUnico = 197, Nombre = "Cruz 1", Texture = "7CROSS", Model = "7cross", price = 300 },
							[2] = {idUnico = 198, Nombre = "Cruz 2", Texture = "7CROSS2", Model = "7cross2", price = 300 },
							[3] = {idUnico = 199, Nombre = "Cruz 3", Texture = "7CROSS3", Model = "7cross3", price = 300 },
							[4] = {idUnico = 200, Nombre = "Virgen María", Texture = "7MARY", Model = "7mary", price = 300 }},
			
			[8] = { 		[1] = {idUnico = 201, Nombre = "Crang Grove", Texture = "8SA", Model = "8sa", price = 500 },
							[2] = {idUnico = 202, Nombre = "Andreas", Texture = "8SA2", Model = "8sa2", price = 500 },
							[3] = {idUnico = 203, Nombre = "San Fierro", Texture = "8SA3", Model = "8sa3", price = 500 },
							-- No funciona, incidencia abierta en MTA #9666
							--[4] = {idUnico = 204, Nombre = "", Texture = "8WESTSD", Model = "8westside", price = 500 },
							-- Tras abrir incidencia en MTA, lo que ha hecho ha sido intercambiar textura y modelo.
							-- Está claro que es un error de MTA, pero como cerraron la incidencia... lo solucionamos nosotros.
							[4] = {idUnico = 204, Nombre = "Westside", Texture = "8westside", Model = "8WESTSD", price = 500 },
							[5] = {idUnico = 205, Nombre = "Los Santos", Texture = "8SANTOS", Model = "8santos", price = 400 },
							[6] = {idUnico = 206, Nombre = "Poker", Texture = "8POKER", Model = "8poker", price = 400 },
							[7] = {idUnico = 207, Nombre = "Gun (AK-47)", Texture = "8GUN", Model = "8gun", price = 400 }},
			
			[9] = { 		[1] = {idUnico = 208, Nombre = "Corona", Texture = "9CROWN", Model = "9crown", price = 200 },
							[2] = {idUnico = 209, Nombre = "Gun 1 (Uzi)", Texture = "9GUN", Model = "9gun", price = 200 },
							[3] = {idUnico = 210, Nombre = "Gun 2 (Colt)", Texture = "9GUN2", Model = "9gun2", price = 200 },
							-- Igual que antes, invertimos textura y modelo.
							--[3] = {idUnico = 211, Nombre = "", Texture = "9HOMBY", Model = "9homeboy", price = 200 },
							--[4] = {idUnico = 212, Nombre = "", Texture = "9BULLT", Model = "9bullet", price = 200 },
							[4] = {idUnico = 211, Nombre = "Homeboy", Texture = "9homeboy", Model = "9HOMBY", price = 200 },
							[5] = {idUnico = 212, Nombre = "Bala", Texture = "9bullet", Model = "9BULLT", price = 200 },
							[6] = {idUnico = 213, Nombre = "Rasta", Texture = "9RASTA", Model = "9rasta", price = 200 }},
			
			[10] = { 		[1] = {idUnico = 214, Nombre = "LS 1", Texture = "10LS", Model = "10ls", price = 200 },
							[2] = {idUnico = 215, Nombre = "LS 2", Texture = "10LS2", Model = "10ls2", price = 200 },
							[3] = {idUnico = 216, Nombre = "LS 3", Texture = "10LS3", Model = "10ls3", price = 200 },
							[4] = {idUnico = 217, Nombre = "LS 4", Texture = "10LS4", Model = "10ls4", price = 200 },
							[5] = {idUnico = 218, Nombre = "LS 5", Texture = "10ls5", Model = "10ls5", price = 200 },
							[6] = {idUnico = 219, Nombre = "OG", Texture = "10OG", Model = "10og", price = 200 },
							[7] = {idUnico = 220, Nombre = "Hierba, Marihuana", Texture = "10WEED", Model = "10weed", price = 200 }},
			
			[11] = { 		[1] = {idUnico = 221, Nombre = "G.S.", Texture = "11GROVE", Model = "11grove", price = 300 },
							-- Intercambio también.
							--[1] = {idUnico = 222, Nombre = "", Texture = "11GROV2", Model = "11grove2", price = 300 },
							--[2] = {idUnico = 223, Nombre = "", Texture = "11GROV3", Model = "11grove3", price = 300 },
							[2] = {idUnico = 222, Nombre = "Grove", Texture = "11grove2", Model = "11GROV2", price = 300 },
							[3] = {idUnico = 223, Nombre = "Grove Street", Texture = "11grove3", Model = "11GROV3", price = 300 },
							[4] = {idUnico = 224, Nombre = "Dados 1", Texture = "11DICE", Model = "11dice", price = 300 },
							[5] = {idUnico = 225, Nombre = "Dados 2", Texture = "11DICE2", Model = "11dice2", price = 300 },
							[6] = {idUnico = 226, Nombre = "Jail", Texture = "11JAIL", Model = "11jail", price = 300 },
							-- Y también.
							--[6] = {idUnico = 227, Nombre = "", Texture = "11GGIFT", Model = "11godsgift", price = 300 }},
							[7] = {idUnico = 227, Nombre = "GodsGift", Texture = "11godsgift", Model = "11GGIFT", price = 300 }},
							
			[12] = { 		[1] = {idUnico = 229, Nombre = "Pájaro Maya", Texture = "12MAYBR", Model = "12mayabird", price = 500 },
							[2] = {idUnico = 230, Nombre = "Daga, cuchillo", Texture = "12DAGER", Model = "12dagger", price = 500 },
							[3] = {idUnico = 231, Nombre = "Máscaras", Texture = "12BNDIT", Model = "12bandit", price = 500 },
							[4] = {idUnico = 232, Nombre = "Cruz", Texture = "12CROSS", Model = "12cross7", price = 500 },
							[5] = {idUnico = 233, Nombre = "Cara Extraña", Texture = "12MYFAC", Model = "12mayafce", price = 500 },
							[6] = {idUnico = 228, Nombre = "Angel", Texture = "12ANGEL", Model = "12angels", price = 500 }},
			
			[13] = { 		[1] = {idUnico = 235, Nombre = "Collar con África", Texture = "neckafrica", Model = "neck", price = 75 },
							[2] = {idUnico = 236, Nombre = "Colalr con Reloj", Texture = "stopwatch", Model = "neck", price = 75 },
							[3] = {idUnico = 237, Nombre = "Collar con Triángulo LS", Texture = "necksaints", Model = "neck", price = 75 },
							[4] = {idUnico = 238, Nombre = "Collar con Marihuana", Texture = "neckhash", Model = "neck", price = 100 },
							[5] = {idUnico = 239, Nombre = "Collar de Plata 1", Texture = "necksilver", Model = "neck2", price = 300 },
							[6] = {idUnico = 240, Nombre = "Collar de Oro 1", Texture = "neckgold", Model = "neck2", price = 750 },
							[7] = {idUnico = 241, Nombre = "Collar de Plata 2", Texture = "neckropes", Model = "neck2", price = 650},
							[8] = {idUnico = 242, Nombre = "Collar de Oro 2", Texture = "neckropeg", Model = "neck2", price = 1000 },
							[9] = {idUnico = 243, Nombre = "Collar con LS", Texture = "neckls", Model = "neck", price = 875 },
							[10] = {idUnico = 244, Nombre = "Collar con $", Texture = "neckdollar", Model = "neck", price = 875 },
							[11] = {idUnico = 245, Nombre = "Collar con Cruz", Texture = "neckcross", Model = "neck", price = 875 },
							[12] = {idUnico = 234, Nombre = "Collar con Chapas", Texture = "dogtag", Model = "neck", price = 75 }},
			
			[14] = { 		[1] = {idUnico = 247, Nombre = "Reloj Amarillo", Texture = "watchyellow", Model = "watch", price = 75 },
							[2] = {idUnico = 248, Nombre = "Reloj Pro 1", Texture = "watchpro", Model = "watch", price = 85 },
							[3] = {idUnico = 249, Nombre = "Reloj Pro 2", Texture = "watchpro2", Model = "watch", price = 85 },
							[4] = {idUnico = 250, Nombre = "Reloj Sub 1", Texture = "watchsub1", Model = "watch", price = 85 },
							[5] = {idUnico = 251, Nombre = "Reloj Sub 2", Texture = "watchsub2", Model = "watch", price = 85 },
							[6] = {idUnico = 252, Nombre = "Reloj ZIP 1", Texture = "watchzip1", Model = "watch", price = 200 },
							[7] = {idUnico = 253, Nombre = "Reloj ZIP 2", Texture = "watchzip2", Model = "watch", price = 200 },
							[8] = {idUnico = 254, Nombre = "Reloj Oro 1", Texture = "watchgno", Model = "watch", price = 375 },
							[9] = {idUnico = 255, Nombre = "Reloj Plata 1", Texture = "watchgno2", Model = "watch", price = 375 },
							[10] = {idUnico = 256, Nombre = "Reloj Oro 2", Texture = "watchpro", Model = "watch", price = 500 },
							[11] = {idUnico = 257, Nombre = "Reloj Plata 2", Texture = "watchpro2", Model = "watch", price = 500 },
							[12] = {idUnico = 246, Nombre = "Reloj Rosa", Texture = "watchpink", Model = "watch", price = 75 }},
			
			[15] = { 		[1] = {idUnico = 259, Nombre = "Antifaz", Texture = "zorro", Model = "zorromask", price = 75 },
							[2] = {idUnico = 260, Nombre = "Parche Pirata", Texture = "eyepatch", Model = "eyepatch", price = 75 },
							[3] = {idUnico = 261, Nombre = "Gafas 1 Transparentes", Texture = "glasses01", Model = "glasses01", price = 100 },
							[4] = {idUnico = 262, Nombre = "Gafas 2 Transparentes", Texture = "glasses04", Model = "glasses04", price = 100 },
							[5] = {idUnico = 263, Nombre = "Pañuelo Rojo", Texture = "bandred3", Model = "bandmask", price = 125 },
							[6] = {idUnico = 264, Nombre = "Pañuelo Azul", Texture = "bandblue3", Model = "bandmask", price = 125 },
							[7] = {idUnico = 265, Nombre = "Pañuelo Verde", Texture = "bandgang3", Model = "bandmask", price = 125 },
							[8] = {idUnico = 266, Nombre = "Pañuelo Negro", Texture = "bandblack3", Model = "bandmask", price = 125 },
							[9] = {idUnico = 267, Nombre = "Gafas 1 Negras", Texture = "glasses01dark", Model = "glasses01", price = 200 },
							[10] = {idUnico = 268, Nombre = "Gafas 2 Negras", Texture = "glasses04dark", Model = "glasses04", price = 200 },
							[11] = {idUnico = 269, Nombre = "Gafas 3 Verdes", Texture = "glasses03", Model = "glasses03", price = 350 },
							[12] = {idUnico = 270, Nombre = "Gafas 3 Rojas", Texture = "glasses03red", Model = "glasses03", price = 350 },
							[13] = {idUnico = 271, Nombre = "Gafas 3 Azules", Texture = "glasses03blue", Model = "glasses03", price = 350 },
							[14] = {idUnico = 272, Nombre = "Gafas 3 Semitransparentes", Texture = "glasses03dark", Model = "glasses03", price = 350 },
							[15] = {idUnico = 273, Nombre = "Gafas 3 Negras", Texture = "glasses05dark", Model = "glasses03", price = 400 },
							[16] = {idUnico = 274, Nombre = "Gafas 4 Semitransparentes", Texture = "glasses05", Model = "glasses03", price = 400 },
							[17] = {idUnico = 258, Nombre = "Máscara (Bigote, Gafas, Nariz)", Texture = "groucho", Model = "grouchos", price = 75 }},
			
			[16] = { 		[1] = {idUnico = 276, Nombre = "Bandana Azul", Texture = "bandblue", Model = "bandana", price = 100 },
							[2] = {idUnico = 277, Nombre = "Bandana Verde", Texture = "bandgang", Model = "bandana", price = 100 },
							[3] = {idUnico = 278, Nombre = "Bandana Negra", Texture = "bandblack", Model = "bandana", price = 100 },
							[4] = {idUnico = 279, Nombre = "Gorro Rojo", Texture = "bandred2", Model = "bandknots", price = 100 },
							[5] = {idUnico = 280, Nombre = "Gorro Azul", Texture = "bandblue2", Model = "bandknots", price = 100 },
							[6] = {idUnico = 281, Nombre = "Gorro Negro", Texture = "bandblack2", Model = "bandknots", price = 100 },
							[7] = {idUnico = 282, Nombre = "Gorro Verde", Texture = "bandgang2", Model = "bandknots", price = 100 },
							[8] = {idUnico = 283, Nombre = "Gorro Lana Gris", Texture = "capknitgrn", Model = "capknit", price = 150 },
							[9] = {idUnico = 284, Nombre = "Gorra Camionero", Texture = "captruck", Model = "captruck", price = 150 },
							[10] = {idUnico = 285, Nombre = "Sombrero Cowboy 1", Texture = "cowboy", Model = "cowboy", price = 150 },
							[11] = {idUnico = 286, Nombre = "Sombrero Cowboy 2", Texture = "hattiger", Model = "cowboy", price = 150 },
							[12] = {idUnico = 287, Nombre = "Casco Rojo", Texture = "helmet", Model = "helmet", price = 450 },
							[13] = {idUnico = 288, Nombre = "Casco Azul", Texture = "moto", Model = "moto", price = 450 },
							[14] = {idUnico = 289, Nombre = "Casco de Boxeo", Texture = "boxingcap", Model = "boxingcap", price = 150},
							[15] = {idUnico = 290, Nombre = "Máscara de Hockey", Texture = "hockey", Model = "hockeymask", price = 150 },
							[16] = {idUnico = 291, Nombre = "Gorra Verde (Delante)", Texture = "capgang", Model = "cap", price = 150 },
							[17] = {idUnico = 292, Nombre = "Gorra Verde (Atrás)", Texture = "capgangback", Model = "capback", price = 150 },
							[18] = {idUnico = 293, Nombre = "Gorra Verde (Lado)", Texture = "capgangside", Model = "capside", price = 150 },
							[19] = {idUnico = 294, Nombre = "Gorra Verde (Torcida)", Texture = "capgangover", Model = "capovereye", price = 150 },
							[20] = {idUnico = 295, Nombre = "Gorra Verde (Doblada)", Texture = "capgangup", Model = "caprimup", price = 150 },
							[21] = {idUnico = 296, Nombre = "Casco de Ciclista", Texture = "bikerhelmet", Model = "bikerhelmet", price = 150 },
							[22] = {idUnico = 297, Nombre = "Gorra Roja (Delante)", Texture = "capred", Model = "cap", price = 150 },
							[23] = {idUnico = 298, Nombre = "Gorra Roja (Atrás)", Texture = "capredback", Model = "capback", price = 150 },
							[24] = {idUnico = 299, Nombre = "Gorra Roja (Lado)", Texture = "capredside", Model = "capside", price = 150 },
							[25] = {idUnico = 300, Nombre = "Gorra Roja (Torcida)", Texture = "capredover", Model = "capovereye", price = 150 },
							[26] = {idUnico = 301, Nombre = "Gorra Roja (Doblada)", Texture = "capredup", Model = "caprimup", price = 150 },
							[27] = {idUnico = 302, Nombre = "Gorra Azul (Delante)", Texture = "capblue", Model = "cap", price = 150 },
							[28] = {idUnico = 303, Nombre = "Gorra Azul (Atrás)", Texture = "capblueback", Model = "capback", price = 150 },
							[29] = {idUnico = 304, Nombre = "Gorra Azul (Lado)", Texture = "capblueside", Model = "capside", price = 150 },
							[30] = {idUnico = 305, Nombre = "Gorra Azul (Torcida)", Texture = "capblueover", Model = "capovereye", price = 150 },
							[31] = {idUnico = 306, Nombre = "Gorra Azul (Doblada)", Texture = "capblueup", Model = "caprimup", price = 150 },
							[32] = {idUnico = 307, Nombre = "Gorro Lana Negro", Texture = "skullyblk", Model = "skullycap", price = 300 },
							[33] = {idUnico = 308, Nombre = "Gorro Lana Verde Oscuro", Texture = "skullygrn", Model = "skullycap", price = 300 },
							[34] = {idUnico = 309, Nombre = "Sombrero Negro 1", Texture = "hatmancblk", Model = "hatmanc", price = 150 },
							[35] = {idUnico = 310, Nombre = "Sombrero Cuadros", Texture = "hatmancplaid", Model = "hatmanc", price = 150 },
							[36] = {idUnico = 311, Nombre = "Gorra Beis (Delante)", Texture = "capzip", Model = "cap", price = 150 },
							[37] = {idUnico = 312, Nombre = "Gorra Beis (Atrás)", Texture = "capzipback", Model = "capback", price = 150 },
							[38] = {idUnico = 313, Nombre = "Gorra Beis (Lado)", Texture = "capzipside", Model = "capside", price = 150 },
							[39] = {idUnico = 314, Nombre = "Gorra Beis (Torcida)", Texture = "capzipover", Model = "capovereye", price = 150 },
							[40] = {idUnico = 315, Nombre = "Gorra Beis (Doblada)", Texture = "capzipup", Model = "caprimup", price = 150 },
							[41] = {idUnico = 316, Nombre = "Boina Roja", Texture = "beretred", Model = "beret", price = 150 },
							[42] = {idUnico = 317, Nombre = "Boina Azul", Texture = "beretblk", Model = "beret", price = 150 },
							[43] = {idUnico = 318, Nombre = "Gorra Negra (Delante)", Texture = "capblk", Model = "cap", price = 150 },
							[44] = {idUnico = 319, Nombre = "Gorra Negra (Atrás)", Texture = "capblkback", Model = "capback", price = 150 },
							[45] = {idUnico = 320, Nombre = "Gorra Negra (Lado)", Texture = "capblkside", Model = "capside", price = 150 },
							[46] = {idUnico = 321, Nombre = "Gorra Negra (Torcida)", Texture = "capblkover", Model = "capovereye", price = 150 },
							[47] = {idUnico = 322, Nombre = "Gorra Negra (Doblada)", Texture = "capblkup", Model = "caprimup", price = 150 },
							[48] = {idUnico = 323, Nombre = "Sombrero Gris", Texture = "trilbydrk", Model = "trilby", price = 200 },
							[49] = {idUnico = 324, Nombre = "Sombrero Blanco", Texture = "trilbylght", Model = "trilby", price = 200 },
							[50] = {idUnico = 325, Nombre = "Sombrero Negro 2", Texture = "bowler", Model = "bowler", price = 200 },
							[51] = {idUnico = 326, Nombre = "Sombrero Rojo", Texture = "bowlerred", Model = "bowler", price = 200 },
							[52] = {idUnico = 327, Nombre = "Sombrero Azul", Texture = "bowlerblue", Model = "bowler", price = 200 },
							[53] = {idUnico = 328, Nombre = "Sombrero Amarillo", Texture = "bowleryellow", Model = "bowler", price = 200 },
							[54] = {idUnico = 329, Nombre = "Sombrero de Paja", Texture = "boater", Model = "boater", price = 200 },
							[55] = {idUnico = 330, Nombre = "Sombrero Verde", Texture = "bowlergang", Model = "bowler", price = 200 },
							[56] = {idUnico = 331, Nombre = "Sombrero de Paja Negro", Texture = "boaterblk", Model = "boater", price = 200 },
							[57] = {idUnico = 275, Nombre = "Bandana Roja", Texture = "bandred", Model = "bandana", price = 100 }},
			
			[17] = { 		[1] = {idUnico = 332, Nombre = "-", Texture = "gimpleg", Model = "gimpleg", price = 3000 },
							[2] = {idUnico = 333, Nombre = "-", Texture = "valet", Model = "valet", price = 3000 },
							[3] = {idUnico = 334, Nombre = "-", Texture = "countrytr", Model = "countrytr", price = 3000 },
							[4] = {idUnico = 335, Nombre = "-", Texture = "croupier", Model = "valet", price = 3000 },
							[5] = {idUnico = 336, Nombre = "-", Texture = "policetr", Model = "policetr", price = 3000 },
							[6] = {idUnico = 337, Nombre = "-", Texture = "balaclava", Model = "balaclava", price = 3000 },
							[7] = {idUnico = 338, Nombre = "-", Texture = "pimptr", Model = "pimptr", price = 3000 },
							[8] = {idUnico = 339, Nombre = "-", Texture = "garageleg", Model = "garagetr", price = 3000 },
							[9] = {idUnico = 340, Nombre = "-", Texture = "medictr", Model = "medictr", price = 3000 }},
							-- Nombre: Lo que lee el usuario. Texture: "SKINHOMBRE" "SKINMUJER" Model="IDSKIN"
			[18] = { 		[1] = {idUnico = 341, Nombre = "Blanco - Hippie anciano. Camiseta a cuadros", Texture = "BAJA", Model = "1", price = 3000 },
							[2] = {idUnico = 342, Nombre = "Blanco - Sobrero blanco con chaqueta a conjunto", Texture = "SKINHOMBRE", Model = "2", price = 3000 },
							[3] = {idUnico = 343, Nombre = "Negro - Chaqueta vaquera y pantalones blancos anchos", Texture = "SKINHOMBRE", Model = "7", price = 3000 },
							[4] = {idUnico = 344, Nombre = "Negra - Anciana. Uniforme formal color café", Texture = "BAJA", Model = "9", price = 3000 },
							[5] = {idUnico = 345, Nombre = "Negra - Anciana gorda. Rebeca a cuadros, falda ortera", Texture = "BAJA", Model = "10", price = 3000 },
							[6] = {idUnico = 346, Nombre = "Negra - Smoking elegante", Texture = "SKINMUJER", Model = "11", price = 3000 },
							[7] = {idUnico = 347, Nombre = "Negra - Vestido corto con tacones", Texture = "SKINMUJER", Model = "12", price = 3000 },
							[8] = {idUnico = 348, Nombre = "Negra - Camiseta morada basket con pantalones deportivos", Texture = "SKINMUJER", Model = "13", price = 3000 },
							[9] = {idUnico = 349, Nombre = "Negro - Camisa a flores y vaqueros café", Texture = "SKINHOMBRE", Model = "14", price = 3000 },
							[10] = {idUnico = 350, Nombre = "Negro - Camisa a cuadros gris y tejanos azules", Texture = "SKINHOMBRE", Model = "15", price = 3000 },
							[11] = {idUnico = 351, Nombre = "Negro - Protectores de sonido y chaleco reflectante", Texture = "SKINHOMBRE", Model = "16", price = 3000 },
							[12] = {idUnico = 352, Nombre = "Negro - Traje elegante", Texture = "SKINHOMBRE", Model = "17", price = 3000 },
							[13] = {idUnico = 353, Nombre = "Negro - Bañador verde y rojo", Texture = "SKINHOMBRE", Model = "18", price = 3000 },
							[14] = {idUnico = 354, Nombre = "Negro - Gorro rojo a juego con pantalones deportivos", Texture = "SKINHOMBRE", Model = "19", price = 3000 },
							[15] = {idUnico = 355, Nombre = "Negro - Conjunto formal, camiseta amarilla y tejanos oscuros", Texture = "SKINHOMBRE", Model = "20", price = 3000 },
							[16] = {idUnico = 356, Nombre = "Negro - Camisa azul, pantalones cortos y vans blancas", Texture = "SKINHOMBRE", Model = "21", price = 3000 },
							[17] = {idUnico = 357, Nombre = "Negro - Gorro, chaqueta basket naranja y pantalones de deporte", Texture = "SKINHOMBRE", Model = "22", price = 3000 },
							[18] = {idUnico = 358, Nombre = "Blanco - Gorra y camiseta skater, pantalones pesqueros y vans blancas", Texture = "SKINHOMBRE", Model = "23", price = 3000 },
							[19] = {idUnico = 359, Nombre = "Negro - Gorra y chaqueta LS azules, pantalones vaqueros", Texture = "SKINHOMBRE", Model = "24", price = 3000 },
							[20] = {idUnico = 360, Nombre = "Negro - Polo azul y blanco, vaqueros azules y converse azules", Texture = "SKINHOMBRE", Model = "25", price = 3000 },
							[21] = {idUnico = 361, Nombre = "Blanco - Ropa de excursión", Texture = "SKINHOMBRE", Model = "26", price = 3000 },
							[22] = {idUnico = 362, Nombre = "Blanco - Casco de obra, guantes robustos y camiseta blanca", Texture = "SKINHOMBRE", Model = "27", price = 3000 },
							[23] = {idUnico = 363, Nombre = "Negro - Gorro de lana, camiseta marron de tirantes y pantalones anchos", Texture = "SKINHOMBRE", Model = "28", price = 3000 },
							[24] = {idUnico = 364, Nombre = "Blanco - Sudadera blanca con capucha y vaqueros caidos", Texture = "SKINHOMBRE", Model = "29", price = 3000 },
							[25] = {idUnico = 365, Nombre = "Blanco - Camiseta de tirantes gris y vaqueros grises altos", Texture = "SKINHOMBRE", Model = "30", price = 3000 },
							[26] = {idUnico = 366, Nombre = "Blanca - Sombrero vaquera blanco, conjunto rurals", Texture = "SKINMUJER", Model = "31", price = 3000 },
							[27] = {idUnico = 367, Nombre = "Blanco - Anciano. Gorra camionero con parche en el ojo. Camisa y pantalones arrugados", Texture = "SKINHOMBRE", Model = "32", price = 3000 },
							[28] = {idUnico = 368, Nombre = "Blanco - Sombrero vaquero negro. Gabardina oscura", Texture = "SKINHOMBRE", Model = "33", price = 3000 },
							[29] = {idUnico = 369, Nombre = "Blanco - Sombrero vaquero oscuro, conjunto rural con camisa a cuadros azul", Texture = "SKINHOMBRE", Model = "34", price = 3000 },
							[30] = {idUnico = 370, Nombre = "Blanco - Camisa rosa, pantalones cortos y botas de montaña", Texture = "SKINHOMBRE", Model = "35", price = 3000 },
							[31] = {idUnico = 371, Nombre = "Blanco - Gorra camionero, camisa blanca y pantalones cortos azules", Texture = "SKINHOMBRE", Model = "36", price = 3000 },
							[32] = {idUnico = 372, Nombre = "Blanco - Gorra roja, polo azul y pantalones cortos", Texture = "SKINHOMBRE", Model = "37", price = 3000 },
							[33] = {idUnico = 373, Nombre = "Blanca - Anciana. Gorro blanco y conjunto pistacho", Texture = "SKINMUJER", Model = "38", price = 3000 },
							[34] = {idUnico = 374, Nombre = "Blanca - Anciana. Chaqueta marron, falda ortera y leggins negros", Texture = "SKINMUJER", Model = "39", price = 3000 },
							[35] = {idUnico = 375, Nombre = "Blanca - Vestido elegante rojo con tacones negross", Texture = "SKINMUJER", Model = "40", price = 3000 },
							[36] = {idUnico = 376, Nombre = "Blanca - Conjunto deportivo azul", Texture = "SKINMUJER", Model = "41", price = 3000 },
							[37] = {idUnico = 377, Nombre = "Blanco - Anciano. Camisa morada y pantalones altos ajustados", Texture = "SKINHOMBRE", Model = "43", price = 3000 },
							[38] = {idUnico = 378, Nombre = "Blanco - Anciano. Camisa azul a cuadros y pantalones marrones", Texture = "SKINHOMBRE", Model = "44", price = 3000 },
							[39] = {idUnico = 379, Nombre = "Blanco - Bañador verde y gafas de sol", Texture = "SKINHOMBRE", Model = "45", price = 3000 },
							[40] = {idUnico = 380, Nombre = "Blanco - Polo blanco y tejanos azules", Texture = "SKINHOMBRE", Model = "46", price = 3000 },
							[41] = {idUnico = 381, Nombre = "Blanco - Camisa marrón, vaqueros beige y gafas de sol", Texture = "SKINHOMBRE", Model = "47", price = 3000 },
							[42] = {idUnico = 382, Nombre = "Blanco - Polo a rayas, blanco y azul", Texture = "SKINHOMBRE", Model = "48", price = 3000 },
							[43] = {idUnico = 383, Nombre = "Blanco - Anciano. Conjunto deportivo asiatico", Texture = "SKINHOMBRE", Model = "49", price = 3000 },
							[44] = {idUnico = 384, Nombre = "Blanco - Mono de mecánico", Texture = "BAJA", Model = "50", price = 3000 },
							[45] = {idUnico = 385, Nombre = "Negro - Uniforme de ciclista amarillo", Texture = "SKINHOMBRE", Model = "51", price = 3000 },
							[46] = {idUnico = 386, Nombre = "Blanco - Uniforme de ciclista blanco", Texture = "SKINHOMBRE", Model = "52", price = 3000 },
							[47] = {idUnico = 387, Nombre = "Blanca - Anciana. Visera blanca, camisa ortera y pantalones cortos", Texture = "SKINMUJER", Model = "53", price = 3000 },
							[48] = {idUnico = 388, Nombre = "Negra - Anciana. Rebeca marrón y falda rosa ortera", Texture = "SKINMUJER", Model = "54", price = 3000 },
							[49] = {idUnico = 389, Nombre = "Blanca - Vestido corto con rayas marrones y negras", Texture = "SKINMUJER", Model = "55", price = 3000 },
							[50] = {idUnico = 390, Nombre = "Blanca - Camiseta de tirantes amarilla, falda oscura y calentadores rosas", Texture = "SKINMUJER", Model = "56", price = 3000 },
							[51] = {idUnico = 391, Nombre = "Blanco - Anciano. Traje elegante", Texture = "SKINHOMBRE", Model = "57", price = 3000 },
							[52] = {idUnico = 392, Nombre = "Blanco - Camisa a cuadros desaliñada y tejanos azules", Texture = "SKINHOMBRE", Model = "58", price = 3000 },
							[53] = {idUnico = 393, Nombre = "Blanco - Camisa a rayas, vaqueros negros y mocasines marrones", Texture = "SKINHOMBRE", Model = "59", price = 3000 },
							[54] = {idUnico = 394, Nombre = "Blanco - Camiseta marrón lisa y vaqueros azules", Texture = "SKINHOMBRE", Model = "60", price = 3000 },
							[55] = {idUnico = 395, Nombre = "Blanco - Uniforme de gala con sombrero", Texture = "SKINHOMBRE", Model = "61", price = 3000 },
							[56] = {idUnico = 396, Nombre = "Blanco - Anciano. Pijama azul a rayas", Texture = "SKINHOMBRE", Model = "62", price = 3000 },
							[57] = {idUnico = 397, Nombre = "Negra - Botas altas, falda corta y sujetador rosa", Texture = "SKINMUJER", Model = "63", price = 3000 },
							[58] = {idUnico = 398, Nombre = "Blanca - Botas cowboy, falda corta y top vaquero", Texture = "SKINMUJER", Model = "64", price = 3000 },
							[59] = {idUnico = 399, Nombre = "Negro - Polo baseball azul y converse", Texture = "SKINHOMBRE", Model = "66", price = 3000 },
							[60] = {idUnico = 400, Nombre = "Negro - Sudadera blanca y pañuelo rojo", Texture = "SKINHOMBRE", Model = "67", price = 3000 },
							[61] = {idUnico = 401, Nombre = "Blanco - Anciano. Sotana negra", Texture = "SKINHOMBRE", Model = "68", price = 3000 },
							[62] = {idUnico = 402, Nombre = "Negra - Chaqueta vaquera y pantalones vaqueros", Texture = "SKINMUJER", Model = "69", price = 3000 },
							[63] = {idUnico = 403, Nombre = "Blanco - Uniforme de doctor con bata blanca", Texture = "BAJA", Model = "70", price = 3000 },
							[64] = {idUnico = 404, Nombre = "Blanco - Uniforme de guardía azul", Texture = "BAJA", Model = "71", price = 3000 },
							[65] = {idUnico = 405, Nombre = "Blanco - Coleta pequeña, camisa a cuadro azul", Texture = "SKINHOMBRE", Model = "72", price = 3000 },
							[66] = {idUnico = 406, Nombre = "Blanco - Camiseta verde, pantalones camuflaje y pañuelo EEUU", Texture = "SKINHOMBRE", Model = "73", price = 3000 },
							[67] = {idUnico = 407, Nombre = "Blanca - Solo tirantes rosas y falda muy corta", Texture = "SKINMUJER", Model = "75", price = 3000 },
							[68] = {idUnico = 408, Nombre = "Negra - Traje elegante con camisa rosa", Texture = "SKINMUJER", Model = "76", price = 3000 },
							[69] = {idUnico = 409, Nombre = "Blanca - Desaliñada, falda rota y chaqueta sucia", Texture = "SKINMUJER", Model = "77", price = 3000 },
							[70] = {idUnico = 410, Nombre = "Blanco - Desaliñado, camisa a cuadros rota y vaqueros estropeados", Texture = "SKINHOMBRE", Model = "78", price = 3000 },
							[71] = {idUnico = 411, Nombre = "Blanco - Desaliñado, gorro de lana y chaleco roto", Texture = "SKINHOMBRE", Model = "79", price = 3000 },
							[72] = {idUnico = 412, Nombre = "Negro - Boxeador", Texture = "SKINHOMBRE", Model = "80", price = 3000 },
							[73] = {idUnico = 413, Nombre = "Blanco - Boxeador", Texture = "SKINHOMBRE", Model = "81", price = 3000 },
							[74] = {idUnico = 414, Nombre = "Blanco - Disfraz negro de Elvis Presley", Texture = "SKINHOMBRE", Model = "82", price = 3000 },
							[75] = {idUnico = 415, Nombre = "Negro - Disfraz blanco de Elvis Presley", Texture = "SKINHOMBRE", Model = "83", price = 3000 },
							[76] = {idUnico = 416, Nombre = "Negro - Disfraz azul de Elvis Presley", Texture = "SKINHOMBRE", Model = "84", price = 3000 },
							[77] = {idUnico = 417, Nombre = "Blanca - Abrigo provocativo y medias de rejilla", Texture = "SKINMUJER", Model = "85", price = 3000 },
							[78] = {idUnico = 418, Nombre = "Blanca - Ropa interior erótica (Peludita)", Texture = "SKINMUJER", Model = "87", price = 3000 },
							[79] = {idUnico = 419, Nombre = "Blanca - Anciana. Polo rojo y pantalones cortos blancos", Texture = "BAJA", Model = "88", price = 3000 },
							[80] = {idUnico = 420, Nombre = "Blanca - Anciana. Vestido azul", Texture = "BAJA", Model = "89", price = 3000 },
							[81] = {idUnico = 421, Nombre = "Blanca - Top deportivo y shorts negros", Texture = "SKINMUJER", Model = "90", price = 3000 },
							[82] = {idUnico = 422, Nombre = "Blanca - Vestido elegante blanco y tacones a conjunto", Texture = "SKINMUJER", Model = "91", price = 3000 },
							[83] = {idUnico = 423, Nombre = "Blanca - Bikini negro y patinetes", Texture = "SKINMUJER", Model = "92", price = 3000 },
							[84] = {idUnico = 424, Nombre = "Blanca - Camiseta negra y jeans oscuros ajustados", Texture = "SKINMUJER", Model = "93", price = 3000 },
							[85] = {idUnico = 425, Nombre = "Blanco - Anciano. Boina blanca, camisa blanca y pantalones cortos", Texture = "SKINHOMBRE", Model = "94", price = 3000 },
							[86] = {idUnico = 426, Nombre = "Blanco - Anciano. Conjunto desaliñado, camisa gris", Texture = "SKINHOMBRE", Model = "95", price = 3000 },
							[87] = {idUnico = 427, Nombre = "Blanco - Conjunto deportivo, camiseta de tirantes y pantalones cortos", Texture = "SKINHOMBRE", Model = "96", price = 3000 },
							[88] = {idUnico = 428, Nombre = "Blanco - Rubio, bañador rojo", Texture = "SKINHOMBRE", Model = "97", price = 3000 },
							[89] = {idUnico = 429, Nombre = "Blanco - Polo informal y vaqueros azules", Texture = "SKINHOMBRE", Model = "98", price = 3000 },
							[90] = {idUnico = 430, Nombre = "Blanco - Conjunto deportivo, casco de bicicleta, mallot", Texture = "SKINHOMBRE", Model = "99", price = 3000 },
							[91] = {idUnico = 431, Nombre = "Blanco - Cabello largo, chaqueta de cuero y botas moteras", Texture = "SKINHOMBRE", Model = "100", price = 3000 },
							[92] = {idUnico = 432, Nombre = "Blanco - Chaqueta oliva, vaqueros negros", Texture = "SKINHOMBRE", Model = "101", price = 3000 },
							[93] = {idUnico = 433, Nombre = "Negro - Camiseta blanca, bandana y pantalones morados", Texture = "SKINHOMBRE", Model = "102", price = 3000 },
							[94] = {idUnico = 434, Nombre = "Negro - Chaqueta negra, bandana morada", Texture = "SKINHOMBRE", Model = "103", price = 3000 },
							[95] = {idUnico = 435, Nombre = "Negro - Chaqueta morada, gorro rasta", Texture = "SKINHOMBRE", Model = "104", price = 3000 },
							[96] = {idUnico = 436, Nombre = "Negro - Sudadera verde con bandana verde", Texture = "SKINHOMBRE", Model = "105", price = 3000 },
							[97] = {idUnico = 437, Nombre = "Negro - Rastas, camiseta a cuadros verde", Texture = "SKINHOMBRE", Model = "106", price = 3000 },
							[98] = {idUnico = 438, Nombre = "Negro - Camiseta basket tirantes verde, gorra", Texture = "SKINHOMBRE", Model = "107", price = 3000 },
							[99] = {idUnico = 439, Nombre = "Blanco - Sin camiseta, bandana amarilla", Texture = "SKINHOMBRE", Model = "108", price = 3000 },
							[100] = {idUnico = 440, Nombre = "Blanco - Camiseta tirantes blanca, bandana amarilla", Texture = "SKINHOMBRE", Model = "109", price = 3000 },
							[101] = {idUnico = 441, Nombre = "Blanco - Camiseta tirantes blanca, vaqueros azul, bandana amarilla", Texture = "SKINHOMBRE", Model = "110", price = 3000 },
							[102] = {idUnico = 442, Nombre = "Blanco - Traje negro", Texture = "SKINHOMBRE", Model = "111", price = 3000 },
							[103] = {idUnico = 443, Nombre = "Blanco - Chaqueta cuero marron, mocasines marrones", Texture = "SKINHOMBRE", Model = "112", price = 3000 },
							[104] = {idUnico = 444, Nombre = "Blanco - Traje elegante azul", Texture = "SKINHOMBRE", Model = "113", price = 3000 },
							[105] = {idUnico = 445, Nombre = "Blanco - Polo a rayas, bandana azul", Texture = "SKINHOMBRE", Model = "114", price = 3000 },
							[106] = {idUnico = 446, Nombre = "Blanco - Chaqueta negra con gorra, bandana azul", Texture = "SKINHOMBRE", Model = "115", price = 3000 },
							[107] = {idUnico = 447, Nombre = "Blanco - Camiseta ancha blanca, bandana azul", Texture = "SKINHOMBRE", Model = "116", price = 3000 },
							[108] = {idUnico = 448, Nombre = "Blanco - Traje negro, asiatico 1", Texture = "SKINHOMBRE", Model = "117", price = 3000 },
							[109] = {idUnico = 449, Nombre = "Blanco - Traje negro, asiatico 2", Texture = "SKINHOMBRE", Model = "118", price = 3000 },
							[110] = {idUnico = 450, Nombre = "Blanco - Traje marron, asiatico 3", Texture = "SKINHOMBRE", Model = "120", price = 3000 },
							[111] = {idUnico = 451, Nombre = "Blanco - Camiseta 'Army' tatuajes, asiatico 4", Texture = "SKINHOMBRE", Model = "121", price = 3000 },
							[112] = {idUnico = 452, Nombre = "Blanco - Camiseta negra, pañuelo negro, asiatico 5", Texture = "SKINHOMBRE", Model = "122", price = 3000 },
							[113] = {idUnico = 453, Nombre = "Blanco - Camiseta china, gafas aviador, asiatico 6", Texture = "SKINHOMBRE", Model = "123", price = 3000 },
							[114] = {idUnico = 454, Nombre = "Blanco - Camiseta negra, vaqueros negros", Texture = "SKINHOMBRE", Model = "124", price = 3000 },
							[115] = {idUnico = 455, Nombre = "Blanco - Chaqueta negra con plieges", Texture = "SKINHOMBRE", Model = "125", price = 3000 },
							[116] = {idUnico = 456, Nombre = "Blanco - Chaqueta negra abierta", Texture = "SKINHOMBRE", Model = "126", price = 3000 },
							[117] = {idUnico = 457, Nombre = "Blanco - Chaqueta marrón abierta y guantes", Texture = "SKINHOMBRE", Model = "127", price = 3000 },
							[118] = {idUnico = 458, Nombre = "Blanco - Camiseta verde, conjunto indio", Texture = "SKINHOMBRE", Model = "128", price = 3000 },
							[119] = {idUnico = 459, Nombre = "Blanca - Anciana. Vestido ortera marrón", Texture = "SKINMUJER", Model = "129", price = 3000 },
							[120] = {idUnico = 460, Nombre = "Blanca - Anciana. Falda roja", Texture = "SKINMUJER", Model = "130", price = 3000 },
							[121] = {idUnico = 461, Nombre = "Blanca - Conjunto rural provocativo", Texture = "SKINMUJER", Model = "131", price = 3000 },
							[122] = {idUnico = 462, Nombre = "Blanco - Anciano. Conjunto indio", Texture = "SKINHOMBRE", Model = "132", price = 3000 },
							[123] = {idUnico = 463, Nombre = "Blanco - Camiseta manga corta marron, gorra camionero", Texture = "SKINHOMBRE", Model = "133", price = 3000 },
							[124] = {idUnico = 464, Nombre = "Negro - Anciano. Conjunto desaliñado, camiseta rota", Texture = "SKINHOMBRE", Model = "134", price = 3000 },
							[125] = {idUnico = 465, Nombre = "Blanco - Conjunto desaliñado, chaqueta roja rota", Texture = "SKINHOMBRE", Model = "135", price = 3000 },
							[126] = {idUnico = 466, Nombre = "Negro - Conjunto desaliñado, bandana reagge y camiseta azul rota", Texture = "SKINHOMBRE", Model = "136", price = 3000 },
							[127] = {idUnico = 467, Nombre = "Blanco - Conjunto desaliñado, caja de carton", Texture = "SKINHOMBRE", Model = "137", price = 3000 },
							[128] = {idUnico = 468, Nombre = "Blanca - Bikini blanco", Texture = "SKINMUJER", Model = "138", price = 3000 },
							[129] = {idUnico = 469, Nombre = "Negra - Bikini amarillo", Texture = "SKINMUJER", Model = "139", price = 3000 },
							[130] = {idUnico = 470, Nombre = "Blanco - Bikini rojo", Texture = "SKINMUJER", Model = "140", price = 3000 },
							[131] = {idUnico = 471, Nombre = "Blanco - Traje elegante negro", Texture = "SKINMUJER", Model = "141", price = 3000 },
							[132] = {idUnico = 472, Nombre = "Negro - Traje Hasam", Texture = "SKINHOMBRE", Model = "142", price = 3000 },
							[133] = {idUnico = 473, Nombre = "Negro - Chaqueta azul, gorro de ducha", Texture = "SKINHOMBRE", Model = "143", price = 3000 },
							[134] = {idUnico = 474, Nombre = "Negro - Camiseta basket negra, mascarilla", Texture = "SKINHOMBRE", Model = "144", price = 3000 },
							[135] = {idUnico = 475, Nombre = "Blanco - Bikini improvisado, mascarilla", Texture = "SKINMUJER", Model = "145", price = 3000 },
							[136] = {idUnico = 476, Nombre = "Blanco - Bañador negro, mascarilla", Texture = "SKINHOMBRE", Model = "146", price = 3000 },
							[137] = {idUnico = 477, Nombre = "Blanco - Traje formal gris", Texture = "SKINHOMBRE", Model = "147", price = 3000 },
							[138] = {idUnico = 478, Nombre = "Negra - Traje formal azul", Texture = "SKINMUJER", Model = "148", price = 3000 },
							[139] = {idUnico = 479, Nombre = "Blanca - Traje formal gris", Texture = "SKINMUJER", Model = "150", price = 3000 },
							[140] = {idUnico = 480, Nombre = "Blanca - Camiseta verde, falda azul. Sobrepeso", Texture = "SKINMUJER", Model = "151", price = 3000 },
							[141] = {idUnico = 481, Nombre = "Blanca - Disfraz colegiala provocativa", Texture = "SKINMUJER", Model = "152", price = 3000 },
							[142] = {idUnico = 482, Nombre = "Blanco - Capataz formal con casco", Texture = "SKINHOMBRE", Model = "153", price = 3000 },
							[143] = {idUnico = 483, Nombre = "Blanco - Bañador azul", Texture = "SKINHOMBRE", Model = "154", price = 3000 },
							[144] = {idUnico = 484, Nombre = "Blanco - Uniforme de pizzero", Texture = "BAJA", Model = "155", price = 3000 },
							[145] = {idUnico = 485, Nombre = "Negro - Camiseta azul cuidada con gafas", Texture = "SKINHOMBRE", Model = "156", price = 3000 },
							[146] = {idUnico = 486, Nombre = "Blanca - Conjunto rural. Peto azul", Texture = "SKINMUJER", Model = "157", price = 3000 },
							[147] = {idUnico = 487, Nombre = "Blanco - Conjunto rural. Peto y sombrero", Texture = "SKINHOMBRE", Model = "158", price = 3000 },
							[148] = {idUnico = 488, Nombre = "Blanco - Conjunto rural. Peto y gorro", Texture = "SKINHOMBRE", Model = "159", price = 3000 },
							[149] = {idUnico = 489, Nombre = "Blanco - Conjunto rural. Camisa a cuadros roja", Texture = "SKINHOMBRE", Model = "160", price = 3000 },
							[150] = {idUnico = 490, Nombre = "Blanco - Conjunto rural. Camisa a cuadros y sombrero", Texture = "SKINHOMBRE", Model = "161", price = 3000 },
							[151] = {idUnico = 491, Nombre = "Blanco - Conjunto rural. Sin camiseta, Pantalones con cuerda", Texture = "SKINHOMBRE", Model = "162", price = 3000 },
							[152] = {idUnico = 492, Nombre = "Negro - Uniforme de seguridad 1", Texture = "SKINHOMBRE", Model = "163", price = 3000 },
							[153] = {idUnico = 493, Nombre = "Blanco - Uniforme de seguridad 2", Texture = "SKINHOMBRE", Model = "164", price = 3000 },
							[154] = {idUnico = 494, Nombre = "Blanco - Uniforme de seguridad 3", Texture = "SKINHOMBRE", Model = "165", price = 3000 },
							[155] = {idUnico = 495, Nombre = "Negro - Uniforme de seguridad 4", Texture = "SKINHOMBRE", Model = "166", price = 3000 },
							[156] = {idUnico = 496, Nombre = "Blanco - Disfraz de pollo", Texture = "SKINHOMBRER", Model = "167", price = 3000 },
							[157] = {idUnico = 497, Nombre = "Negro - Delantal manchado y gorra hacía atrás", Texture = "SKINHOMBRE", Model = "168", price = 3000 },
							[158] = {idUnico = 498, Nombre = "Blanca - Vestido asiatico elegante", Texture = "SKINMUJER", Model = "169", price = 3000 },
							[159] = {idUnico = 499, Nombre = "Blanco - Camiseta roja y pantalones grises", Texture = "SKINHOMBRE", Model = "170", price = 3000 },
							[160] = {idUnico = 500, Nombre = "Blanco - Smoking elegante", Texture = "SKINHOMBRE", Model = "171", price = 3000 },
							[161] = {idUnico = 501, Nombre = "Blanca - Smoking elegante, rubia", Texture = "SKINMUJER", Model = "172", price = 3000 },
							[162] = {idUnico = 502, Nombre = "Blanco - Tirantes negros, sombrero y bandana azul", Texture = "SKINHOMBRE", Model = "173", price = 3000 },
							[163] = {idUnico = 503, Nombre = "Blanco - Chaqueta de cuero y bandana azul", Texture = "SKINHOMBRE", Model = "174", price = 3000 },
							[164] = {idUnico = 504, Nombre = "Blanco - Camisa azul con tirantes y bandana azul", Texture = "SKINHOMBRE", Model = "175", price = 3000 },
							[165] = {idUnico = 505, Nombre = "Negro - Camiseta azul, barba recortada", Texture = "SKINHOMBRE", Model = "176", price = 3000 },
							[166] = {idUnico = 506, Nombre = "Blanco - Camiseta azul, cabello cuidado", Texture = "SKINHOMBRE", Model = "177", price = 3000 },
							[167] = {idUnico = 507, Nombre = "Blanca - Uniforme bondage provocativo", Texture = "SKINMUJER", Model = "178", price = 3000 },
							[168] = {idUnico = 508, Nombre = "Blanco - Conjunto verde y botas militares", Texture = "SKINHOMBRE", Model = "179", price = 3000 },
							[169] = {idUnico = 509, Nombre = "Negro - Camiseta basket roja y negra", Texture = "SKINHOMBRE", Model = "180", price = 3000 },
							[170] = {idUnico = 510, Nombre = "Blanco - Conjunto punk", Texture = "SKINHOMBRE", Model = "181", price = 3000 },
							[171] = {idUnico = 511, Nombre = "Negro - Camisa a rayas, pantalones cortos. Desaliñado", Texture = "SKINHOMBRE", Model = "182", price = 3000 },
							[172] = {idUnico = 512, Nombre = "Negro - Camisa a cuadros marron, rastas cortas", Texture = "SKINHOMBRE", Model = "183", price = 3000 },
							[173] = {idUnico = 513, Nombre = "Blanco - Camiseta a rayas. Vaqueros blancos", Texture = "SKINHOMBRE", Model = "184", price = 3000 },
							[174] = {idUnico = 514, Nombre = "Negro - Camisa a rayas moradas, pantalones negros lisos", Texture = "SKINHOMBRE", Model = "185", price = 3000 },
							[175] = {idUnico = 515, Nombre = "Blanco - Conjunto formal marron", Texture = "SKINHOMBRE", Model = "186", price = 3000 },
							[176] = {idUnico = 516, Nombre = "Blanco - Conjunto formal azul a rayas", Texture = "SKINHOMBRE", Model = "187", price = 3000 },
							[177] = {idUnico = 517, Nombre = "Blanco - Camiseta azul turquesa, vaqueros", Texture = "SKINHOMBRE", Model = "188", price = 3000 },
							[178] = {idUnico = 518, Nombre = "Blanco - Smoking rojo", Texture = "SKINHOMBRE", Model = "189", price = 3000 },
							[179] = {idUnico = 519, Nombre = "Negra - Conjunto deportivo. Top rojo y leggins negros", Texture = "SKINMUJER", Model = "190", price = 3000 },
							[180] = {idUnico = 520, Nombre = "Blanca - Camiseta verde, pantalones cargo y botas militares", Texture = "SKINMUJER", Model = "191", price = 3000 },
							[181] = {idUnico = 521, Nombre = "Blanca - Camiseta escotada y vaqueros negros", Texture = "SKINMUJER", Model = "192", price = 3000 },
							[182] = {idUnico = 522, Nombre = "Blanca - Conjunto deportivo. Tirantes rojos y pantalones grises", Texture = "SKINMUJER", Model = "193", price = 3000 },
							[183] = {idUnico = 523, Nombre = "Blanca - Smoking elegante", Texture = "SKINMUJER", Model = "194", price = 3000 },
							[184] = {idUnico = 524, Nombre = "Negra - Camiseta basket, pantalones deportivos blancos", Texture = "SKINMUJER", Model = "195", price = 3000 },
							[185] = {idUnico = 525, Nombre = "Blanca - Anciana. Falda ortera marron", Texture = "SKINMUJER", Model = "196", price = 3000 },
							[186] = {idUnico = 526, Nombre = "Blanca - Anciana. Falda ortera roja, sobrepeso", Texture = "SKINMUJER", Model = "197", price = 3000 },
							[187] = {idUnico = 527, Nombre = "Blanca - Conjunto rural, gorro y botas cowboy", Texture = "SKINMUJER", Model = "198", price = 3000 },
							[188] = {idUnico = 528, Nombre = "Blanca - Anciana. Pijama rosa", Texture = "SKINMUJER", Model = "199", price = 3000 },
							[189] = {idUnico = 529, Nombre = "Blanco - Anciano. Conjunto desaliñado roto", Texture = "SKINHOMBRE", Model = "200", price = 3000 },
							[190] = {idUnico = 530, Nombre = "Blanca - Conjunto rural provocativo", Texture = "SKINMUJER", Model = "201", price = 3000 },
							[191] = {idUnico = 531, Nombre = "Blanco - Gorra camionero, camiseta gris y azul", Texture = "SKINHOMBRE", Model = "202", price = 3000 },
							[192] = {idUnico = 532, Nombre = "Blanco - Conjunto deportivo asiatico 1", Texture = "SKINHOMBRE", Model = "203", price = 3000 },
							[193] = {idUnico = 533, Nombre = "Blanco - Conjunto deportivo asiatico 2", Texture = "SKINHOMBRE", Model = "204", price = 3000 },
							[194] = {idUnico = 534, Nombre = "Blanca - Disfraz de hamburguesa", Texture = "SKINMUJER", Model = "205", price = 3000 },
							[195] = {idUnico = 535, Nombre = "Blanco - Camiseta camionero, vaqueros", Texture = "SKINHOMBRE", Model = "206", price = 3000 },
							[196] = {idUnico = 536, Nombre = "Blanca - Top corto verde, falda corta", Texture = "SKINMUJER", Model = "207", price = 3000 },
							[197] = {idUnico = 537, Nombre = "Blanco - Anciano. Conjunto de vendedor", Texture = "SKINHOMBRE", Model = "209", price = 3000 },
							[198] = {idUnico = 538, Nombre = "Blanco - Camisa azul y vaqueros oscuros", Texture = "SKINHOMBRE", Model = "210", price = 3000 },
							[199] = {idUnico = 539, Nombre = "Blanca - Camiseta azul y blanca, vaqueros negros", Texture = "SKINMUJER", Model = "211", price = 3000 },
							[200] = {idUnico = 540, Nombre = "Blanco - Anciano. Bañador colorido, sudadera verde", Texture = "SKINHOMBRE", Model = "212", price = 3000 },
							[201] = {idUnico = 541, Nombre = "Blanco - Conjunto Elvis blanco roto", Texture = "SKINHOMBRE", Model = "213", price = 3000 },
							[202] = {idUnico = 542, Nombre = "Negra - Vestido blanco corto y tacones blancos", Texture = "SKINMUJER", Model = "214", price = 3000 },
							[203] = {idUnico = 543, Nombre = "Negra  - Camisa amarilla,pantalones blancos,gorro blanco", Texture = "SKINMUJER", Model = "215", price = 3000 },
							[204] = {idUnico = 544, Nombre = "Blanca - Vestido lila corto", Texture = "SKINMUJER", Model = "216", price = 3000 },
							[205] = {idUnico = 545, Nombre = "Blanco - Camiseta negra y pantalones anchos negros", Texture = "SKINHOMBRE", Model = "217", price = 3000 },
							[206] = {idUnico = 546, Nombre = "Negra  - Ancina. Falda cruces azul/marron, camisa rosa y chaleco marron ", Texture = "SKINMUJER", Model = "218", price = 3000 },
							[207] = {idUnico = 547, Nombre = "Negra  - Traje rojo elegante corto", Texture = "SKINMUJER", Model = "219", price = 3000 },
							[208] = {idUnico = 548, Nombre = "Negro  - Anciano.Pantalones cortos beis, camisa ancha morada y taguia-gorro ", Texture = "BAJA", Model = "220", price = 3000 },
							[209] = {idUnico = 549, Nombre = "Negro  - Vaquero azul y camisa blanca", Texture = "SKINHOMBRE", Model = "221", price = 3000 },
							[210] = {idUnico = 550, Nombre = "Negro  - Vaquero gris, camiseta negra y de colores", Texture = "SKINHOMBRE", Model = "222", price = 3000 },
							[211] = {idUnico = 551, Nombre = "Blanco - Vaquero oscuro, camisa morada y accesorios de oro", Texture = "SKINHOMBRE", Model = "223", price = 3000 },
							[212] = {idUnico = 552, Nombre = "Blanca - Conjunto asiatico morado femenino y tacones negros", Texture = "SKINMUJER", Model = "224", price = 3000 },
							[213] = {idUnico = 553, Nombre = "Blanca - Vaquero celeste, camisa colorida de puntos y zapatos deportivos", Texture = "SKINMUJER", Model = "225", price = 3000 },
							[214] = {idUnico = 554, Nombre = "Blanca - Camiseta tirantes lila, falda negra y calentadores", Texture = "SKINMUJER", Model = "226", price = 3000 },
							[215] = {idUnico = 555, Nombre = "Blanco - Anciano. Traje gris oscuro elegante y corbata azul", Texture = "SKINHOMBRE", Model = "227", price = 3000 },
							[216] = {idUnico = 556, Nombre = "Blanco - Anciano. Traje negro y corbata morada", Texture = "SKINHOMBRE", Model = "228", price = 3000 },
							[217] = {idUnico = 557, Nombre = "Blanco - Anciano. Vaqueros grises y camisa blanca con trazas negras", Texture = "SKINHOMBRE", Model = "229", price = 3000 },
							[218] = {idUnico = 558, Nombre = "Negro  - Sudadera negra, pantalones rotos, vendas mugrientas y cartel colgado", Texture = "SKINHOMBRE", Model = "230", price = 3000 },
							[219] = {idUnico = 559, Nombre = "Blanca - Anciana. Camisa verde gastada y falda roja a cuadros", Texture = "SKINMUJER", Model = "231", price = 3000 },
							[220] = {idUnico = 560, Nombre = "Blanca - Anciana. Chaqueta a cuadros roja, falda a rayas rojas y medias amarillas", Texture = "SKINMUJER", Model = "232", price = 3000 },
							[221] = {idUnico = 561, Nombre = "Blanca - Camiseta blanca y vaqueros celestes", Texture = "SKINMUJER", Model = "233", price = 3000 },
							[222] = {idUnico = 562, Nombre = "Blanco - Camiseta beis, gafas de sol y vaqueros celeste", Texture = "SKINHOMBRE", Model = "234", price = 3000 },
							[223] = {idUnico = 563, Nombre = "Blanco - Anciano. Camisa de colores oscuros, pantalones beis", Texture = "SKINHOMBRE", Model = "235", price = 3000 },
							[224] = {idUnico = 564, Nombre = "Blanco - Anciano. Camisa verde a cuadros y vaqueros marrones", Texture = "SKINHOMBRE", Model = "236", price = 3000 },
							[225] = {idUnico = 565, Nombre = "Blanca - Conjunto provocativo. Falda negra y chaqueta de leopardo", Texture = "SKINMUJER", Model = "237", price = 3000 },
							[226] = {idUnico = 566, Nombre = "Negra  - Conjunto provocativo. Vestido de latex rojo y botas altas rojas", Texture = "SKINMUJER", Model = "238", price = 3000 },
							[227] = {idUnico = 567, Nombre = "Blanco - Anciano. Conjunto desaliñado, camisa a cuadros, vaqueros celestes", Texture = "SKINHOMBRE", Model = "239", price = 3000 },
							[228] = {idUnico = 568, Nombre = "Blanco - Chaleco negro, camisa blanca y pantalones negros", Texture = "SKINHOMBRE", Model = "240", price = 3000 },
							[229] = {idUnico = 569, Nombre = "Blanco - Sobrepeso, camisa negra abierta y piratas grises claros", Texture = "SKINHOMBRE", Model = "241", price = 3000 },
							[230] = {idUnico = 570, Nombre = "Blanco - Sobrepeso, camisa blanca de tirantes y piratas negros", Texture = "SKINHOMBRE", Model = "242", price = 3000 },
							[231] = {idUnico = 571, Nombre = "Blanca - Conjunto provocativo, top rojo, falda negra", Texture = "BAJA", Model = "243", price = 3000 },
							[232] = {idUnico = 572, Nombre = "Negra  - Conjunto provocativo, sujetador blanco, guantes largos y medias blancas", Texture = "BAJA", Model = "244", price = 3000 },
							[233] = {idUnico = 573, Nombre = "Negra  - Conjunto provocativo, top blanco y falda roja corta", Texture = "SKINMUJER", Model = "245", price = 3000 },
							[234] = {idUnico = 574, Nombre = "Blanca - Conjunto de latex negro provocativo y gorra de policia, botas negras altas", Texture = "SKINMUJER", Model = "246", price = 3000 },
							[235] = {idUnico = 575, Nombre = "Blanco - Conjunto motero, chaleco negro sin mangas, botas militares y pañuelo negro", Texture = "SKINHOMBRE", Model = "247", price = 3000 },
							[236] = {idUnico = 576, Nombre = "Blanco - Conjunto motero, chaqueta negra, guantes, cinta roja en cabeza", Texture = "SKINHOMBRE", Model = "248", price = 3000 },
							[237] = {idUnico = 577, Nombre = "Negro  - Abrigo de pelos, corbata roja, pantalones negros y gorro blanco", Texture = "SKINHOMBRE", Model = "249", price = 3000 },
							[238] = {idUnico = 578, Nombre = "Blanco - Camiseta verde, camiseta negra interior, vaqueros grises y zapatos deportivos", Texture = "SKINHOMBRE", Model = "250", price = 3000 },
							[239] = {idUnico = 579, Nombre = "Blanca - Bikini rojo de socorrista", Texture = "SKINMUJER", Model = "251", price = 3000 },
							[240] = {idUnico = 580, Nombre = "Blanco - Calzoncillos de corazones rojos", Texture = "BAJA", Model = "252", price = 3000 },
							[241] = {idUnico = 581, Nombre = "Negro  - Traje de conserje azul marino y franjas amarillas", Texture = "SKINHOMBRE", Model = "253", price = 3000 },
							[242] = {idUnico = 582, Nombre = "Blanco - Conjunto motero, chaleco negro sin mangas 2, botas militares y pañuelo negro", Texture = "SKINHOMBRE", Model = "254", price = 3000 },
							[243] = {idUnico = 583, Nombre = "Blanco - Traje de chofer negro y gorra de chofer", Texture = "SKINHOMBRE", Model = "255", price = 3000 },
							[244] = {idUnico = 584, Nombre = "Negra  - Conjunto provocativo de colegiala", Texture = "SKINMUJER", Model = "256", price = 3000 },
							[245] = {idUnico = 585, Nombre = "Blanca - Conjunto provocativo de latex negro, medias y tacones negros", Texture = "SKINMUJER", Model = "257", price = 3000 },
							[246] = {idUnico = 586, Nombre = "Blanco - Camisa de cuadros gris por dentro, vaqueros beis y zapatos beis", Texture = "SKINHOMBRE", Model = "258", price = 3000 },
							[247] = {idUnico = 587, Nombre = "Blanco - Camisa de cuadros azul por fuera, pantalones cortos beis y zapatos azules", Texture = "SKINHOMBRE", Model = "259", price = 3000 },
							[248] = {idUnico = 588, Nombre = "Negro  - Chaleco naranja de obra, pantalon negro y casco de obra", Texture = "SKINHOMBRE", Model = "260", price = 3000 },
							[249] = {idUnico = 589, Nombre = "Blanco - Camisa gris oscura de cuadros, vaquero gris y gorra gris", Texture = "SKINHOMBRE", Model = "261", price = 3000 },
							[250] = {idUnico = 590, Nombre = "Negro  - Camisa verde abierta, camiseta de tirantes blancas y pantalones grises", Texture = "SKINHOMBRE", Model = "262", price = 3000 },
							[251] = {idUnico = 591, Nombre = "Blanca - Traje asiatico negro-amarillo femenino", Texture = "SKINMUJER", Model = "263", price = 3000 },
							[252] = {idUnico = 592, Nombre = "Blanco - Conjunto de payaso blanco-rojo", Texture = "SKINHOMBRE", Model = "264", price = 3000 },
							[253] = {idUnico = 593, Nombre = "Negro  - Uniforme policia tenpen", Texture = "BAJA", Model = "265", price = 3000 },
							[254] = {idUnico = 594, Nombre = "Blanco - Uniforme policia pulaski", Texture = "BAJA", Model = "266", price = 3000 },
							[255] = {idUnico = 595, Nombre = "Negro  - Uniforme policia hern", Texture = "BAJA", Model = "267", price = 3000 },
							[256] = {idUnico = 596, Nombre = "Blanco - Traje azul marino de mecanico", Texture = "BAJA", Model = "268", price = 3000 },
							[257] = {idUnico = 597, Nombre = "Negro  - Sobrepeso, camisa verde, pantalones negros y bombin", Texture = "SKINHOMBRE", Model = "269", price = 3000 },
							[258] = {idUnico = 598, Nombre = "Negro  - Camiseta verde, vaqueros negro y gorra verde", Texture = "BAJA", Model = "270", price = 3000 },
							[259] = {idUnico = 599, Nombre = "Negro  - Sudadera verde, pantalones negros, gafas de sol y gorra negra", Texture = "BAJA", Model = "271", price = 3000 },
							[260] = {idUnico = 600, Nombre = "Blanco - Chaqueta de cuero marron, polo oscuro, pantalones de pana beis", Texture = "BAJA", Model = "272", price = 3000 },
							[261] = {idUnico = 601, Nombre = "Negro  - Uniforme medico blanco y pantalones azules", Texture = "BAJA", Model = "274", price = 3000 },
							[262] = {idUnico = 602, Nombre = "Negro  - Uniforme azul y pantalones azules", Texture = "BAJA", Model = "275", price = 3000 },
							-- A PARTIR DE AQUI HAY AVERIA
							[263] = {idUnico = 603, Nombre = "Blanco - Uniforme verde y pantalones verdes", Texture = "BAJA", Model = "276", price = 3000 },
							[264] = {idUnico = 604, Nombre = "Blanco - Uniforme bombero claro y casco amarillo", Texture = "BAJA", Model = "277", price = 3000 },
							[265] = {idUnico = 605, Nombre = "Negro  - Uniforme bombero claro y casco negro", Texture = "BAJA", Model = "278", price = 3000 },
							[266] = {idUnico = 606, Nombre = "Negro  - Uniforme bombero oscuro y casco oscuro", Texture = "BAJA", Model = "279", price = 3000 },
							[267] = {idUnico = 607, Nombre = "Blanco - Uniforme policia generico negro", Texture = "BAJA", Model = "280", price = 3000 },
							[268] = {idUnico = 608, Nombre = "Blanco - Uniforme sheriff ciudad negro", Texture = "BAJA", Model = "281", price = 3000 },
							[269] = {idUnico = 609, Nombre = "Blanco - Uniforme policia beis", Texture = "BAJA", Model = "282", price = 3000 },
							[270] = {idUnico = 610, Nombre = "Blanco - Uniforme policia marron sheriff, gorro vaquero", Texture = "BAJA", Model = "283", price = 3000 },
							[271] = {idUnico = 611, Nombre = "Blanco - Uniforme policia motero", Texture = "BAJA", Model = "284", price = 3000 },
							[272] = {idUnico = 612, Nombre = "Blanco - Uniforme policia SWAT", Texture = "BAJA", Model = "285", price = 3000 },
							[273] = {idUnico = 613, Nombre = "Blanco - Uniforme policia FBI", Texture = "BAJA", Model = "286", price = 3000 },
							[274] = {idUnico = 614, Nombre = "Blanco - Uniforme militar camuflaje, gorra militar", Texture = "BAJA", Model = "287", price = 3000 },
							[275] = {idUnico = 615, Nombre = "Blanco - Uniforme sheriff beis, pantalones verdes y gorro vaquero", Texture = "BAJA", Model = "288", price = 3000 },
							[276] = {idUnico = 616, Nombre = "Blanco - Chaqueta negra, pantalones beis y zapatos marrones", Texture = "BAJA", Model = "290", price = 3000 },
							[277] = {idUnico = 617, Nombre = "Blanco - Chaleco vaquero azul, camiseta blanca de tirantes, vaqueros negros y converse rojas", Texture = "BAJA", Model = "291", price = 3000 },
							[278] = {idUnico = 618, Nombre = "Negro  - Camiseta blanca de tirantes, pantalones grises y deportivas blancas", Texture = "BAJA", Model = "292", price = 3000 },
							[279] = {idUnico = 619, Nombre = "Negro  - Sin camiseta, pantalones marrones y collar de oro", Texture = "BAJA", Model = "293", price = 3000 },
							[280] = {idUnico = 620, Nombre = "Blanco - Traje elegante negro y gafas de sol", Texture = "BAJA", Model = "294", price = 3000 },
							[281] = {idUnico = 621, Nombre = "Blanco - Chaqueta negra, corbata roja, pantalones marrones claros y zapatos negros", Texture = "BAJA", Model = "295", price = 3000 },
							[282] = {idUnico = 622, Nombre = "Negro  - Traje purpura, zapatos blancos", Texture = "BAJA", Model = "296", price = 3000 },
							[283] = {idUnico = 623, Nombre = "Negro  - Sudadera azul oscuro, vaqueros azules y zapatos deportivos blancos", Texture = "BAJA", Model = "297", price = 3000 },
							[284] = {idUnico = 624, Nombre = "Negra  - Camiseta de tirantas negra, pantalones negros deportivos y sandalias", Texture = "BAJA", Model = "298", price = 3000 },
							[285] = {idUnico = 625, Nombre = "Blanco - Chaqueta de cuero negra, camiseta negra, pantalones verdes claro y converse", Texture = "BAJA", Model = "299", price = 3000 },
							[286] = {idUnico = 626, Nombre = "Negro  - Sudadera verde, pantalones negros, gafas de sol y gorra negra", Texture = "BAJA", Model = "300", price = 3000 },
							[287] = {idUnico = 627, Nombre = "Negro  - Sudadera verde, pantalones negros, gafas de sol y media negra en cabeza", Texture = "BAJA", Model = "301", price = 3000 },
							[288] = {idUnico = 628, Nombre = "Negro  - Chaqueta verde oliva, camiseta blanca, vaquero negro y gorro rojo", Texture = "BAJA", Model = "302", price = 3000 },
							[289] = {idUnico = 629, Nombre = "Blanco - Chaqueta azul, camiseta de colores, pantalon verde oliva y deportivas blancas", Texture = "BAJA", Model = "303", price = 3000 },
							[290] = {idUnico = 630, Nombre = "Negra  - Camiseta beisbol negra, pantalones anchos negros y gorro marron", Texture = "BAJA", Model = "304", price = 3000 },
							[291] = {idUnico = 631, Nombre = "Blanco - Traje mecanico azul celeste, pañuelo americano", Texture = "BAJA", Model = "305", price = 3000 },
							[292] = {idUnico = 632, Nombre = "Blanco - Chaqueta verde, camiseta negra, piratas negros y gafas", Texture = "SKINHOMBRE", Model = "306", price = 3000 },
							[293] = {idUnico = 633, Nombre = "Negro  - Camiseta a rayas blanca y negra, vaqueros grises", Texture = "SKINHOMBRE", Model = "307", price = 3000 },
							[294] = {idUnico = 634, Nombre = "Blanco - Chaqueta azul oscuro, pantalones beis y zapatos marrones", Texture = "SKINHOMBRE", Model = "308", price = 3000 },
							[295] = {idUnico = 635, Nombre = "Negro  - Traje mecanico rojo y gorro rojo", Texture = "BAJA", Model = "309", price = 3000 },
							[296] = {idUnico = 636, Nombre = "Negro  - Camisa marron corta, vaqueros azules y deportivos blancos", Texture = "SKINHOMBRE", Model = "310", price = 3000 },
							[297] = {idUnico = 637, Nombre = "Negro  - Sobrepeso, camiseta verde, vaqueros negros, chaleco tactico y bombin", Texture = "SKINHOMBRE", Model = "311", price = 3000 },
							[298] = {idUnico = 638, Nombre = "Blanco - Chaqueta verde, pantalones camuflaje, botas militares y gorro negro", Texture = "SKINHOMBRE", Model = "312", price = 3000 }
							}}
							
addEvent("displayclothes",true)
addEventHandler("displayclothes",getRootElement(),
function(style)
	if client and source and client == source then
		local sql, err = exports.sql:query_assoc_single("SELECT color, genero FROM characters WHERE characterID = "..tostring(exports.players:getCharacterID(source)))
		local color = tonumber(sql.color)
		local genero = tonumber(sql.genero)
		triggerClientEvent(client,"displayClothOn",client,clothes[style], style, tonumber(genero), tonumber(color))
	end
end)

function getIdUnico(textura)
	if textura then
		for i = 0, 18 do
			for k, v in ipairs(clothes[i]) do
				if tostring(v.Texture) == tostring(textura) then
					return tonumber(v.idUnico)
				end
			end
		end
	end
end

function getInfoRopa(idUnico)
	if idUnico then
		for i = 0, 18 do
			for k, v in ipairs(clothes[i]) do
				if tostring(v.idUnico) == tostring(idUnico) then
					return tostring(v.Texture), tostring(v.Model), tonumber(i)
				end
			end
		end
	end
end

addEventHandler("onMarkerHit",getRootElement(),
function(hitElement)
	if (source == clothmarker1) or (source == clothmarker2) then
		if getElementType(hitElement) == "player" and not isPedInVehicle(hitElement) then
			if getElementDimension(hitElement) == getElementDimension(source) then
				local sql, err = exports.sql:query_assoc_single("SELECT color, genero FROM characters WHERE characterID = "..tostring(exports.players:getCharacterID(hitElement)))
				--local color = tonumber(sql.color)
				local genero = tonumber(sql.genero)
				triggerClientEvent(hitElement,"showDemClothGui", hitElement, genero)
				exports.objetivos:addObjetivo(10, exports.players:getCharacterID(hitElement), hitElement)
			end
		end
	end
end) 

addEvent("aplicarRopaServidor",true)
addEventHandler("aplicarRopaServidor",getRootElement(),
function(idUnico)
	if idUnico then
		local sql = exports.sql:query_assoc_single("SELECT color FROM characters WHERE characterID = "..tostring(exports.players:getCharacterID(source)))
		local color = tonumber(sql.color)
		if idUnico <= 0 then
			if getElementModel(source) > 0 then
				setElementModel(source, 0)
			end
			removePedClothes(source, -idUnico)
			if color == 1 then -- Blanco
				triggerClientEvent("onSolicitarRopaBlanco", source)
			end
		else
			if idUnico >= 341 then -- Skin de las antiguas.
				if idUnico == 99999 then
					setElementModel(source, 0)
					if color == 1 then -- Blanco
						triggerClientEvent("onSolicitarRopaBlanco", source)
					end
				else
					local _, skin = getInfoRopa(tonumber(idUnico))
					--outputDebugString("IDUnico: "..tonumber(idUnico))
					--outputDebugString("IDSkin: "..tonumber(skin))
					setElementModel(source, tonumber(skin))
				end
			else
				if getElementModel(source) > 0 then
					setElementModel(source, 0)
				end
				local textura, modelo, tipo = getInfoRopa(tonumber(idUnico))
				addPedClothes(source,textura,modelo,tipo)
				if color == 1 then -- Blanco
					triggerClientEvent("onSolicitarRopaBlanco", source)
				end
			end
		end
		exports.ropas:saveClothes(source)
	end 
end)