local root = getRootElement()

addEventHandler("onClientResourceStart",root,function()
	lift_txd = engineLoadTXD("file/vehiclelift.txd")
	engineImportTXD(lift_txd,2597)
	hoist_dff = engineLoadDFF("file/hoist.dff",2597)
	engineReplaceModel(hoist_dff,2597)
	hoist_col = engineLoadCOL("file/hoist.col")
	engineReplaceCOL(hoist_col,2597)
	engineImportTXD(lift_txd,2231)
	ramp_dff = engineLoadDFF("file/ramp.dff",2231)
	engineReplaceModel(ramp_dff,2231)
	ramp_col = engineLoadCOL("file/ramp.col")
	engineReplaceCOL(ramp_col,2231)
end)